apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
- name: target-cluster
  type: target
  targetType: landscaper.gardener.cloud/kubernetes-cluster

deployExecutions:
- name: nginx-execution
  file: /deploy-execution-nginx.yaml
  type: GoTemplate
