apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint
jsonSchema: "https://json-schema.org/draft/2019-09/schema"

imports:
  - name: cluster  # "cluster" is the name of the import parameter
    type: target
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: release  # "release" is the name of the import parameter
    type: data
    schema:
      type: object
      properties:
        name:
          type: string
        namespace:
          type: string

  - name: values  # "values" is  the name of the import parameter
    type: data
    schema:
      type: object

deployExecutions:
  - name: default
    type: GoTemplate
    file: /deploy-execution.yaml
