# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

jsonSchema: "https://json-schema.org/draft/2019-09/schema" # required

localTypes:
  resourceDef:
    type: object
    properties:
      memory:
        type: string
      cpu:
        type: string

imports:
- name: dnsClass
  type: data
  required: false
  schema:
    type: string

- name: namespace
  type: data
  default:
    value: kube-system
  schema:
    type: string

- name: cluster
  type: target
  targetType: kubernetes-cluster

- name: resources
  type: data
  required: false
  schema:
    type: object
    properties:
      requests:
        $ref: "local://resourceDef"
      limits:
        $ref: "local://resourceDef"

exports:
- name: ingressClass
  type: data
  schema:
    type: string

- name: exported-cluster
  type: target
  targetType: landscaper.gardener.cloud/kubernetes-cluster

# List of deploy item generators
# The generators return list of deploy items that are aggregated.
# Be aware that all deploy items must have a unique key
# otherwise the aggregation will return an error.
deployExecutions:
  # todo: add values export
- type: go-template
  file: /deployItems.yaml # virtual filesystem

exportExecutions:
- type: go-template
  template: |
    ingressClass: {{ .exports.deployitems.deploy.ingressClass }}
    exported-cluster:
      labels: {}
      annotations: {}
      config:
        kubeconfig: {{ .exports.deployitems.deploy.kubeconfig  }}
