apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint
jsonSchema: "https://json-schema.org/draft/2019-09/schema"

imports:
  - name: cluster                                             # name of the import parameter
    targetType: landscaper.gardener.cloud/kubernetes-cluster  # type of the import parameter

deployExecutions:
  - name: default
    type: GoTemplate
    template: |
      deployItems:
        - name: default-deploy-item
          type: landscaper.gardener.cloud/helm
      
          target:
            import: cluster   # "cluster" is the name of an import parameter
      
          config:
            apiVersion: helm.deployer.landscaper.gardener.cloud/v1alpha1
            kind: ProviderConfiguration
            name: hello-world
            namespace: example
            chart:
              ref: eu.gcr.io/gardener-project/landscaper/examples/charts/hello-world:1.0.0
            values:
              testData: hello
