{{/* SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.global.serviceAccount.webhooksServer.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "landscaper.webhooksServer.serviceAccountName" . }}
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - "validatingwebhookconfigurations"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "*"
{{- end }}
