{{/* SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.user.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "landscaper.user.serviceAccountName" . }}
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "landscaper.user.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "landscaper.user.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
