apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint
jsonSchema: "https://json-schema.org/draft/2019-09/schema"

imports:
  - name: cluster                                             # name of the import parameter
    targetType: landscaper.gardener.cloud/kubernetes-cluster  # type of the import parameter

deployExecutions:
  - name: default-deploy-execution
    file: /deploy-execution.yaml
    type: GoTemplate
