# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "landscaper.main.fullname" . }}
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "landscaper.main.fullname" . }}
  minReplicas: 1
  maxReplicas: {{ .Values.hpaMain.maxReplicas }}
  metrics:
  {{- .Values.hpaMain.metrics | toYaml | nindent 4 }}
