{{/* SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

{{- if and (.Values.global.serviceAccount.controller.create) (.Values.controller.landscaperKubeconfig) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "landscaper.controller.serviceAccountName" . }}
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
  {{- with .Values.global.serviceAccount.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
