component:
  repositoryBaseUrl: europe-docker.pkg.dev/sap-gcp-cp-k8s-stable-hub/landscaper-examples/examples
  name: github.com/gardener/landscaper-examples/guided-tour/automation/simple-helm
  version: 1.0.0

items:
  echo-server:
    type: helm
    createNamespace: true
    chart:
      name: echo-server-chart
      access:
        type: ociArtifact
        imageReference: europe-docker.pkg.dev/sap-gcp-cp-k8s-stable-hub/landscaper-examples/examples/charts/guided-tour/echo-server:1.0.0
    images:
      echo-server-image: hashicorp/http-echo:0.2.3
    additionalValues: |
      foo:
        img: {{ $images.echo-server-image }}
        bar: 42
