# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Component
metadata:
  name: ingress-controller
spec:
  blueprintRef: nginx-ingress-controller

  imports:
  - from: .kubeconfigs.base
    type: kubeconfig
    to: .kubeconfig

  - from: .dep.helmchart.ingress-controller
    type: helmchart
    to: .helmchart.ingress-controller
  - from: .dep.image.nginx-ingress-controller
    type: image
    to: .images.nginx-ingress-controller

  - from: .dns.class
    type: string
    to: .dnsClass
  - from: .ingress.resources
    to: .resources
    type: ResourceRequirements
    required: false

  exports:
  - to: .ingress.class
    type: string
    from: .ingressClass