component:
  repositoryBaseUrl: europe-docker.pkg.dev/sap-gcp-cp-k8s-stable-hub/landscaper-examples/examples
  name: github.com/gardener/landscaper-examples/guided-tour/automation/simple-helm
  version: 1.0.0

externalImports:
  imported-token:
    schema:
      type: string

externalExports:
  public-token:
    type: string
    value: |
      {{ $exports.echo-server-extended.token }}

items:
  echo-server-extended:
    type: helm
    createNamespace: true
    chart:
      name: echo-server-chart
      type: helmChart
      version: 1.0.0
      access:
        type: ociArtifact
        imageReference: europe-docker.pkg.dev/sap-gcp-cp-k8s-stable-hub/landscaper-examples/examples/charts/guided-tour/echo-server-extended:1.0.0
    images:
      echo-server-image: hashicorp/http-echo:0.2.3
    additionalValues: |
      sub1:
        ima: {{ $images.echo-server-image }}
        sub3: 42
    readinessChecks:
      ...
    exports:
      token:
        schema:
          type: string
        fromResource:
          apiVersion: v1
          kind: Secret
          name: test-secret
          isNamespaces: true
          # namespace: example #optional: if isNamespaced==true and not set use the relase namespace
        jsonPath: .data.token

  next-chart:
    type: helm
    createNamespace: true
    chart:
      name: next-chart
      type: helmChart
      version: 1.0.0
      access:
        type: ociArtifact
        imageReference: europe-docker.pkg.dev/sap-gcp-cp-k8s-stable-hub/landscaper-examples/examples/charts/guided-tour/next-chart:1.0.0
    images:
      next-chart-image: guided-tour/next-image:0.2.3
    imports:
      imported-token:
        schema:
          type: string
        from-item: echo-server-extended
        from-export: token
    additionalValues: |
      sub1:
        image: {{ $images.next-chart-image }}
        sub2: {{ $imports.imported-token }}
        sub3: {{ $externalImports.imported-token }}
