apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: echo-server
  namespace: example
  annotations:
    landscaper.gardener.cloud/operation: reconcile

spec:
  context: landscaper-examples

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-examples/guided-tour/echo-server
      version: 1.3.0

  blueprint:
    ref:
      resourceName: blueprint

  # Set value for the target import parameter "cluster" of the blueprint
  imports:
    targets:
      - name: cluster        # name of an import parameter of the blueprint
        target: my-cluster   # name of the Target custom resource containing the kubeconfig of the target cluster

  # Set values for the import parameters "release" and "text" of the blueprint
  importDataMappings:
    release:
      name: echo
      namespace: example
    text: hello
