# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: my-aggregation
spec:
  blueprint:
    ref:
      repositoryContext:
        type: ociRegistry
        baseUrl: eu.gcr.io/my-project/comp
      componentName: github.com/gardener/landscaper/simple-aggregated
      version: v0.1.0
      resourceName: simple-aggregated

  imports:
    targets:
    - name: aggCluster
      # the "#" forces the landscaper to use the target with the name "my-cluster" in the same namespace
      target: "#my-cluster"

  exports:
    data:
    - name: aggIngressClass
      dataRef: "myAggIngressClass"