// +build !ignore_autogenerated

/*
Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	json "encoding/json"
	unsafe "unsafe"

	corev1alpha1 "github.com/gardener/landscaper/pkg/apis/core/v1alpha1"
	helm "github.com/gardener/landscaper/pkg/apis/deployer/helm"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ExportFromManifestItem)(nil), (*helm.ExportFromManifestItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExportFromManifestItem_To_helm_ExportFromManifestItem(a.(*ExportFromManifestItem), b.(*helm.ExportFromManifestItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*helm.ExportFromManifestItem)(nil), (*ExportFromManifestItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_helm_ExportFromManifestItem_To_v1alpha1_ExportFromManifestItem(a.(*helm.ExportFromManifestItem), b.(*ExportFromManifestItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProviderConfiguration)(nil), (*helm.ProviderConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProviderConfiguration_To_helm_ProviderConfiguration(a.(*ProviderConfiguration), b.(*helm.ProviderConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*helm.ProviderConfiguration)(nil), (*ProviderConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_helm_ProviderConfiguration_To_v1alpha1_ProviderConfiguration(a.(*helm.ProviderConfiguration), b.(*ProviderConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProviderStatus)(nil), (*helm.ProviderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProviderStatus_To_helm_ProviderStatus(a.(*ProviderStatus), b.(*helm.ProviderStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*helm.ProviderStatus)(nil), (*ProviderStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_helm_ProviderStatus_To_v1alpha1_ProviderStatus(a.(*helm.ProviderStatus), b.(*ProviderStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ExportFromManifestItem_To_helm_ExportFromManifestItem(in *ExportFromManifestItem, out *helm.ExportFromManifestItem, s conversion.Scope) error {
	out.Key = in.Key
	out.JSONPath = in.JSONPath
	out.FromResource = (*corev1alpha1.TypedObjectReference)(unsafe.Pointer(in.FromResource))
	return nil
}

// Convert_v1alpha1_ExportFromManifestItem_To_helm_ExportFromManifestItem is an autogenerated conversion function.
func Convert_v1alpha1_ExportFromManifestItem_To_helm_ExportFromManifestItem(in *ExportFromManifestItem, out *helm.ExportFromManifestItem, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExportFromManifestItem_To_helm_ExportFromManifestItem(in, out, s)
}

func autoConvert_helm_ExportFromManifestItem_To_v1alpha1_ExportFromManifestItem(in *helm.ExportFromManifestItem, out *ExportFromManifestItem, s conversion.Scope) error {
	out.Key = in.Key
	out.JSONPath = in.JSONPath
	out.FromResource = (*corev1alpha1.TypedObjectReference)(unsafe.Pointer(in.FromResource))
	return nil
}

// Convert_helm_ExportFromManifestItem_To_v1alpha1_ExportFromManifestItem is an autogenerated conversion function.
func Convert_helm_ExportFromManifestItem_To_v1alpha1_ExportFromManifestItem(in *helm.ExportFromManifestItem, out *ExportFromManifestItem, s conversion.Scope) error {
	return autoConvert_helm_ExportFromManifestItem_To_v1alpha1_ExportFromManifestItem(in, out, s)
}

func autoConvert_v1alpha1_ProviderConfiguration_To_helm_ProviderConfiguration(in *ProviderConfiguration, out *helm.ProviderConfiguration, s conversion.Scope) error {
	out.Kubeconfig = in.Kubeconfig
	out.Repository = in.Repository
	out.Version = in.Version
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Values = *(*json.RawMessage)(unsafe.Pointer(&in.Values))
	out.ExportsFromManifests = *(*[]helm.ExportFromManifestItem)(unsafe.Pointer(&in.ExportsFromManifests))
	return nil
}

// Convert_v1alpha1_ProviderConfiguration_To_helm_ProviderConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ProviderConfiguration_To_helm_ProviderConfiguration(in *ProviderConfiguration, out *helm.ProviderConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProviderConfiguration_To_helm_ProviderConfiguration(in, out, s)
}

func autoConvert_helm_ProviderConfiguration_To_v1alpha1_ProviderConfiguration(in *helm.ProviderConfiguration, out *ProviderConfiguration, s conversion.Scope) error {
	out.Kubeconfig = in.Kubeconfig
	out.Repository = in.Repository
	out.Version = in.Version
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Values = *(*json.RawMessage)(unsafe.Pointer(&in.Values))
	out.ExportsFromManifests = *(*[]ExportFromManifestItem)(unsafe.Pointer(&in.ExportsFromManifests))
	return nil
}

// Convert_helm_ProviderConfiguration_To_v1alpha1_ProviderConfiguration is an autogenerated conversion function.
func Convert_helm_ProviderConfiguration_To_v1alpha1_ProviderConfiguration(in *helm.ProviderConfiguration, out *ProviderConfiguration, s conversion.Scope) error {
	return autoConvert_helm_ProviderConfiguration_To_v1alpha1_ProviderConfiguration(in, out, s)
}

func autoConvert_v1alpha1_ProviderStatus_To_helm_ProviderStatus(in *ProviderStatus, out *helm.ProviderStatus, s conversion.Scope) error {
	out.ManagedResources = *(*[]corev1alpha1.TypedObjectReference)(unsafe.Pointer(&in.ManagedResources))
	return nil
}

// Convert_v1alpha1_ProviderStatus_To_helm_ProviderStatus is an autogenerated conversion function.
func Convert_v1alpha1_ProviderStatus_To_helm_ProviderStatus(in *ProviderStatus, out *helm.ProviderStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProviderStatus_To_helm_ProviderStatus(in, out, s)
}

func autoConvert_helm_ProviderStatus_To_v1alpha1_ProviderStatus(in *helm.ProviderStatus, out *ProviderStatus, s conversion.Scope) error {
	out.ManagedResources = *(*[]corev1alpha1.TypedObjectReference)(unsafe.Pointer(&in.ManagedResources))
	return nil
}

// Convert_helm_ProviderStatus_To_v1alpha1_ProviderStatus is an autogenerated conversion function.
func Convert_helm_ProviderStatus_To_v1alpha1_ProviderStatus(in *helm.ProviderStatus, out *ProviderStatus, s conversion.Scope) error {
	return autoConvert_helm_ProviderStatus_To_v1alpha1_ProviderStatus(in, out, s)
}
