# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

jsonSchema: "https://json-schema.org/draft/2019-09/schema" # required

imports:
- name: providers
  type: data
  required: false
  schema:
    type: array
    items:
      $ref: cd://componentReferences/schemas/resources/schemas#definitions/provider # cd://componentReferences/github.com/gardener/external-dns-management-schemas/resources/schemas#definitions/provider

- name: dnsClass
  type: data
  required: false
  schema:
    type: string

- name: identifier
  type: data
  required: false
  example: ... # optional
  schema:
    description: ""
    type: string
- name: namespace
  type: data
  default:
    value: kube-system
  schema:
    type: string

- name: cluster
  type: target
  targetType: landscaper.cloud/kubernetes-cluster # schema definition
  subTypes:
    - gardener
    - seed

exports:
- name: dnsClass
  type: data
  schema:
    type: string

- name: myTarget
  type: target
  targetType: landscaper.cloud/kubernetes-cluster

# List of deploy item generators
# The generators return list of deploy items that are aggregated.
# Be aware that all deploy items must have a unique key
# otherwise the aggregation will return an error.
deployExecutions:
# - type: go-template
#   file: /my/path/cc # virtual filesystem
#   template: |
#     my template: {{ .Values.abc }}

# - type: container
#   image: localResource/my-templater
#   command: "asdf"

- name: my-exec
  type: Spiff
  stubs:
  - "/my/stubfile/..."
  - "cd://componentReference/my-other-comp/localResource/..."
  file: /installer.yaml # virtual filesystem
  # template:
  #   a:
  #     b: (( readFile() ))

exportExecutions:
# - type: go-template # returns list of deploy items
#   file: /my/path/cc # virtual filesystem
#   template: |
#     my template: {{ .Values.abc }}
 - type: GoTemplate
   template: |
     dnsClass: {{ .deployitem.installer.myexports }}
     url: https://{{ .deployitem.installer.myexports }}:{{ .dataobjects.port }}
