apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
  - name: gardenerServiceAccount
    required: true
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: name
    required: true
    type: data
    schema:
      type: string

  - name: namespace
    required: true
    type: data
    schema:
      type: string

  - name: secretBindingName
    required: true
    type: data
    schema:
      type: string

  - name: labels
    required: false
    type: data
    schema:
      type: object

  - name: shootConfig
    required: true
    type: data
    schema:
      $ref: "cd://resources/shoot-config-definition"

  - name: auditPolicy
    required: false
    type: data
    schema:
      type: object

  - name: subaccountId
    required: false
    type: data
    schema:
      type: string

exports:
  - name: shootClusterKubeconfig
    type: data
    schema:
      type: string

  - name: shootClusterEndpoint
    type: data
    schema:
      type: string

  - name: shootCluster
    type: target
    targetType: landscaper.gardener.cloud/kubernetes-cluster

deployExecutions:
  - name: deploy-execution
    file: /deploy-execution.yaml
    type: GoTemplate

exportExecutions:
  - name: export-execution
    file: /export-execution.yaml
    type: GoTemplate
