apiVersion: landscaper.gardener.cloud/v1alpha1
kind: DeployItem
metadata:
  name: my-nginx
spec:
  type: Helm
  target:
    name: my-cluster
    namespace: default
  config:
    apiVersion: helm.deployer.landscaper.gardener.cloud/v1alpha1
    kind: ProviderConfiguration

    chart:
      ref: eu.gcr.io/myproject/charts/nginx-ingress:0.5.2

    name: test
    namespace: default

    exportsFromManifests:
    - key: ingressClass
      jsonPath: Values.controller.ingressClass
    - key: prometheus.port
      jsonPath: spec.template.metadata.annotations['prometheus\.io/port']
      fromResource:
        apiVersion: apps/v1
        kind: Deployment
        name: test-nginx-ingress
        namespace: default
