# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: landscaper.gardener.cloud/v1alpha1
kind: DeployItem
metadata:
  name: state
spec:
  type: landscaper.gardener.cloud/container

  config:
    apiVersion: container.deployer.landscaper.gardener.cloud/v1alpha1
    kind: ProviderConfiguration

    image: alpine
    command: ["sh", "-c"]
    args:
    - |
      ls -la $STATE_PATH
      export COUNTER=0
      if [ -f "$STATE_PATH/counter" ]; then export COUNTER=$(cat "$STATE_PATH/counter"); fi
      export COUNTER=$((COUNTER+1))
      echo $COUNTER > $STATE_PATH/counter
      echo "{ \"counter\": $COUNTER }" > $EXPORTS_PATH

    importValues: abc
