apiVersion: landscaper.gardener.cloud/v1alpha1
kind: DeployItem
metadata:
  name: ref
spec:
  type: Container

  config:
    apiVersion: container.deployer.landscaper.gardener.cloud/v1alpha1
    kind: ProviderConfiguration

    blueprint:
      ref:
        repositoryContext:
          baseUrl: eu.gcr.io/myproject/gci-test
          type: ociRegistry
        componentName: simple
        version: 0.1.0
        kind: localResource
        resourceName: simple

    registryPullSecrets:
    - name: gcr-dev
      namespace: default

    importValues: abc

    image: alpine
    command: ["sh", "-c"]
    args:
    - |
      env
      ls -laR $CONTENT_PATH
