# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: landscaper.gardener.cloud/v1alpha1
kind: DeployItem
metadata:
  name: ref
spec:
  type: landscaper.gardener.cloud/container

  config:
    apiVersion: container.deployer.landscaper.gardener.cloud/v1alpha1
    kind: ProviderConfiguration

    blueprint:
      ref:
        repositoryContext:
          baseUrl: eu.gcr.io/gardener-project/landscaper/tutorials/components/
          type: ociRegistry
        componentName: github.com/gardener/landscaper/ingress-nginx
        version: v0.1.0
        resourceName: ingress-nginx-blueprint

    registryPullSecrets:
    - name: gcr-dev
      namespace: default

    importValues: abc

    image: alpine
    command: ["sh", "-c"]
    args:
    - |
      env
      ls -laR $CONTENT_PATH
      ls -laR $REGISTRY_SECRETS_DIR
