apiVersion: landscaper.gardener.cloud/v1alpha1
kind: DeployItem
metadata:
  name: my-secret
spec:
  type: Manifest

  target:
    name: my-cluster
    namespace: default

  config:
    apiVersion: manifest.deployer.landscaper.gardener.cloud/v1alpha1
    kind: ProviderConfiguration

    manifests: # list of kubernetes manifests
    - apiVersion: v1
      kind: Secret
      metadata:
        name: my-secret
        namespace: default
      stringData:
        config: my-val
