# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: landscaper.gardener.cloud/v1alpha1
kind: DeployItem
metadata:
  name: my-secret
spec:
  type: landscaper.gardener.cloud/kubernetes-manifest

  target:
    name: my-cluster
    namespace: default

  config:
    apiVersion: manifest.deployer.landscaper.gardener.cloud/v1alpha1
    kind: ProviderConfiguration

    manifests: # list of kubernetes manifests
    - apiVersion: v1
      kind: Secret
      metadata:
        name: my-secret
        namespace: default
      stringData:
        config: my-val
