// +build !ignore_autogenerated

/*
Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

SPDX-License-Identifier: Apache-2.0
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v2 "github.com/gardener/component-spec/bindings-go/apis/v2"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"

	config "github.com/gardener/landscaper/apis/config"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*LandscaperConfiguration)(nil), (*config.LandscaperConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LandscaperConfiguration_To_config_LandscaperConfiguration(a.(*LandscaperConfiguration), b.(*config.LandscaperConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.LandscaperConfiguration)(nil), (*LandscaperConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_LandscaperConfiguration_To_v1alpha1_LandscaperConfiguration(a.(*config.LandscaperConfiguration), b.(*LandscaperConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LocalRegistryConfiguration)(nil), (*config.LocalRegistryConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LocalRegistryConfiguration_To_config_LocalRegistryConfiguration(a.(*LocalRegistryConfiguration), b.(*config.LocalRegistryConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.LocalRegistryConfiguration)(nil), (*LocalRegistryConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_LocalRegistryConfiguration_To_v1alpha1_LocalRegistryConfiguration(a.(*config.LocalRegistryConfiguration), b.(*LocalRegistryConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OCICacheConfiguration)(nil), (*config.OCICacheConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OCICacheConfiguration_To_config_OCICacheConfiguration(a.(*OCICacheConfiguration), b.(*config.OCICacheConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.OCICacheConfiguration)(nil), (*OCICacheConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_OCICacheConfiguration_To_v1alpha1_OCICacheConfiguration(a.(*config.OCICacheConfiguration), b.(*OCICacheConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OCIConfiguration)(nil), (*config.OCIConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OCIConfiguration_To_config_OCIConfiguration(a.(*OCIConfiguration), b.(*config.OCIConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.OCIConfiguration)(nil), (*OCIConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_OCIConfiguration_To_v1alpha1_OCIConfiguration(a.(*config.OCIConfiguration), b.(*OCIConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RegistryConfiguration)(nil), (*config.RegistryConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RegistryConfiguration_To_config_RegistryConfiguration(a.(*RegistryConfiguration), b.(*config.RegistryConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.RegistryConfiguration)(nil), (*RegistryConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_RegistryConfiguration_To_v1alpha1_RegistryConfiguration(a.(*config.RegistryConfiguration), b.(*RegistryConfiguration), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_LandscaperConfiguration_To_config_LandscaperConfiguration(in *LandscaperConfiguration, out *config.LandscaperConfiguration, s conversion.Scope) error {
	out.RepositoryContext = (*v2.RepositoryContext)(unsafe.Pointer(in.RepositoryContext))
	out.DefaultOCI = (*config.OCIConfiguration)(unsafe.Pointer(in.DefaultOCI))
	if err := Convert_v1alpha1_RegistryConfiguration_To_config_RegistryConfiguration(&in.Registry, &out.Registry, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LandscaperConfiguration_To_config_LandscaperConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_LandscaperConfiguration_To_config_LandscaperConfiguration(in *LandscaperConfiguration, out *config.LandscaperConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_LandscaperConfiguration_To_config_LandscaperConfiguration(in, out, s)
}

func autoConvert_config_LandscaperConfiguration_To_v1alpha1_LandscaperConfiguration(in *config.LandscaperConfiguration, out *LandscaperConfiguration, s conversion.Scope) error {
	out.RepositoryContext = (*v2.RepositoryContext)(unsafe.Pointer(in.RepositoryContext))
	out.DefaultOCI = (*OCIConfiguration)(unsafe.Pointer(in.DefaultOCI))
	if err := Convert_config_RegistryConfiguration_To_v1alpha1_RegistryConfiguration(&in.Registry, &out.Registry, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_LandscaperConfiguration_To_v1alpha1_LandscaperConfiguration is an autogenerated conversion function.
func Convert_config_LandscaperConfiguration_To_v1alpha1_LandscaperConfiguration(in *config.LandscaperConfiguration, out *LandscaperConfiguration, s conversion.Scope) error {
	return autoConvert_config_LandscaperConfiguration_To_v1alpha1_LandscaperConfiguration(in, out, s)
}

func autoConvert_v1alpha1_LocalRegistryConfiguration_To_config_LocalRegistryConfiguration(in *LocalRegistryConfiguration, out *config.LocalRegistryConfiguration, s conversion.Scope) error {
	out.RootPath = in.RootPath
	return nil
}

// Convert_v1alpha1_LocalRegistryConfiguration_To_config_LocalRegistryConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_LocalRegistryConfiguration_To_config_LocalRegistryConfiguration(in *LocalRegistryConfiguration, out *config.LocalRegistryConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_LocalRegistryConfiguration_To_config_LocalRegistryConfiguration(in, out, s)
}

func autoConvert_config_LocalRegistryConfiguration_To_v1alpha1_LocalRegistryConfiguration(in *config.LocalRegistryConfiguration, out *LocalRegistryConfiguration, s conversion.Scope) error {
	out.RootPath = in.RootPath
	return nil
}

// Convert_config_LocalRegistryConfiguration_To_v1alpha1_LocalRegistryConfiguration is an autogenerated conversion function.
func Convert_config_LocalRegistryConfiguration_To_v1alpha1_LocalRegistryConfiguration(in *config.LocalRegistryConfiguration, out *LocalRegistryConfiguration, s conversion.Scope) error {
	return autoConvert_config_LocalRegistryConfiguration_To_v1alpha1_LocalRegistryConfiguration(in, out, s)
}

func autoConvert_v1alpha1_OCICacheConfiguration_To_config_OCICacheConfiguration(in *OCICacheConfiguration, out *config.OCICacheConfiguration, s conversion.Scope) error {
	out.UseInMemoryOverlay = in.UseInMemoryOverlay
	out.Path = in.Path
	return nil
}

// Convert_v1alpha1_OCICacheConfiguration_To_config_OCICacheConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_OCICacheConfiguration_To_config_OCICacheConfiguration(in *OCICacheConfiguration, out *config.OCICacheConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_OCICacheConfiguration_To_config_OCICacheConfiguration(in, out, s)
}

func autoConvert_config_OCICacheConfiguration_To_v1alpha1_OCICacheConfiguration(in *config.OCICacheConfiguration, out *OCICacheConfiguration, s conversion.Scope) error {
	out.UseInMemoryOverlay = in.UseInMemoryOverlay
	out.Path = in.Path
	return nil
}

// Convert_config_OCICacheConfiguration_To_v1alpha1_OCICacheConfiguration is an autogenerated conversion function.
func Convert_config_OCICacheConfiguration_To_v1alpha1_OCICacheConfiguration(in *config.OCICacheConfiguration, out *OCICacheConfiguration, s conversion.Scope) error {
	return autoConvert_config_OCICacheConfiguration_To_v1alpha1_OCICacheConfiguration(in, out, s)
}

func autoConvert_v1alpha1_OCIConfiguration_To_config_OCIConfiguration(in *OCIConfiguration, out *config.OCIConfiguration, s conversion.Scope) error {
	out.ConfigFiles = *(*[]string)(unsafe.Pointer(&in.ConfigFiles))
	out.Cache = (*config.OCICacheConfiguration)(unsafe.Pointer(in.Cache))
	out.AllowPlainHttp = in.AllowPlainHttp
	return nil
}

// Convert_v1alpha1_OCIConfiguration_To_config_OCIConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_OCIConfiguration_To_config_OCIConfiguration(in *OCIConfiguration, out *config.OCIConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_OCIConfiguration_To_config_OCIConfiguration(in, out, s)
}

func autoConvert_config_OCIConfiguration_To_v1alpha1_OCIConfiguration(in *config.OCIConfiguration, out *OCIConfiguration, s conversion.Scope) error {
	out.ConfigFiles = *(*[]string)(unsafe.Pointer(&in.ConfigFiles))
	out.Cache = (*OCICacheConfiguration)(unsafe.Pointer(in.Cache))
	out.AllowPlainHttp = in.AllowPlainHttp
	return nil
}

// Convert_config_OCIConfiguration_To_v1alpha1_OCIConfiguration is an autogenerated conversion function.
func Convert_config_OCIConfiguration_To_v1alpha1_OCIConfiguration(in *config.OCIConfiguration, out *OCIConfiguration, s conversion.Scope) error {
	return autoConvert_config_OCIConfiguration_To_v1alpha1_OCIConfiguration(in, out, s)
}

func autoConvert_v1alpha1_RegistryConfiguration_To_config_RegistryConfiguration(in *RegistryConfiguration, out *config.RegistryConfiguration, s conversion.Scope) error {
	out.Local = (*config.LocalRegistryConfiguration)(unsafe.Pointer(in.Local))
	out.OCI = (*config.OCIConfiguration)(unsafe.Pointer(in.OCI))
	return nil
}

// Convert_v1alpha1_RegistryConfiguration_To_config_RegistryConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_RegistryConfiguration_To_config_RegistryConfiguration(in *RegistryConfiguration, out *config.RegistryConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_RegistryConfiguration_To_config_RegistryConfiguration(in, out, s)
}

func autoConvert_config_RegistryConfiguration_To_v1alpha1_RegistryConfiguration(in *config.RegistryConfiguration, out *RegistryConfiguration, s conversion.Scope) error {
	out.Local = (*LocalRegistryConfiguration)(unsafe.Pointer(in.Local))
	out.OCI = (*OCIConfiguration)(unsafe.Pointer(in.OCI))
	return nil
}

// Convert_config_RegistryConfiguration_To_v1alpha1_RegistryConfiguration is an autogenerated conversion function.
func Convert_config_RegistryConfiguration_To_v1alpha1_RegistryConfiguration(in *config.RegistryConfiguration, out *RegistryConfiguration, s conversion.Scope) error {
	return autoConvert_config_RegistryConfiguration_To_v1alpha1_RegistryConfiguration(in, out, s)
}
