#!/bin/bash

# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

echo "create dummy component descriptor"

SOURCE_PATH="$(dirname $0)/.."
VERSION="$(${SOURCE_PATH}/hack/get-version.sh)"
REPO_CTX="eu.gcr.io/gardener-project/development"
COMPONENT_DESCRIPTOR_DIR="${SOURCE_PATH}/../${COMPONENT_DESCRIPTOR_DIR}"

VERSION="${VERSION}-dummy" REPO_CTX="${REPO_CTX}" COMPONENT_DESCRIPTOR_DIR="${COMPONENT_DESCRIPTOR_DIR}" python ${SOURCE_PATH}/hack/create-dummy-cd.py

echo "create real component descriptor"

${SOURCE_PATH}/.ci/component_descriptor_real
