#!/bin/bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

PROJECT_ROOT="$(realpath $(dirname $0)/..)"
REPOSITORY_CONTEXT="europe-docker.pkg.dev/sap-gcp-cp-k8s-stable-hub/landscaper"

source "$PROJECT_ROOT/.ci/ensure-go"
"$PROJECT_ROOT/.ci/ensure-make"

# start docker daemon
launch-dockerd.sh

# configure credentials
mkdir -p "$HOME/.docker"
gardener-ci docker cfg --image "${REPOSITORY_CONTEXT}" > $HOME/.docker/config.json

(
  cd "$PROJECT_ROOT"
  make revendor build-resources
)
