#!/bin/bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

SOURCE_PATH="$(dirname $0)/.."

curl -s https://ocm.software/install.sh | bash

curl -s https://get.docker.com | bash
service docker start

${SOURCE_PATH}/hack/generate-cd.sh
