#!/bin/bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

SOURCE_PATH="$(dirname $0)/.."

curl -s https://ocm.software/install.sh | bash
apt-get install docker-ce docker-ce-cli

${SOURCE_PATH}/hack/generate-cd.sh
