#!/bin/sh

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# Helper script executing the integration tests in the context of a Gardener Concours pipeline job with access to the cc-config.
# It is called by the scripts integration-test and integration-test-new and installs some required software and calls
# .../hack/integration-test.py. The script requires an ID for $1 which is integrated in the name of the test shoot cluster.
# The cluster name has the format it-pr$PR_ID-<4-digits>.

set -euo pipefail

PROJECT_ROOT="$(realpath $(dirname $0)/..)"

PR_ID=$1
export PR_ID

echo "Starting Landscaper integration tests in $PROJECT_ROOT"

# install bash for the get version command
if ! which bash 1>/dev/null; then
  echo "Installing bash... "
  apk add --no-cache --no-progress bash
fi

if ! command -v python3 &> /dev/null
then
    echo "Python3 could not be found"
    echo "Try installing it..."
    apk add -q --no-cache --no-progress python3 python3-dev py3-pip gcc libc-dev libffi-dev openssl-dev cargo build-base
fi

echo "Running pip3 install --upgrade pip"
pip3 install -q --upgrade pip

echo "Running pip3 install gardener-cicd-libs"
pip3 install -q gardener-cicd-libs

VERSION="$(./hack/get-version.sh)"
export VERSION

"$PROJECT_ROOT/hack/integration-test.py"

