#!/bin/bash

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

GARDENER_KUBECONFIG_PATH=$1
NAMESPACE=$2
VERSION=$3
PR_ID=$4

MAX_NUM_CLUSTERS=20
NUM_CLUSTERS_START_DELETE_OLDEST=15
DURATION_FOR_CLUSTER_DELETION=48h

SOURCE_PATH="$(realpath $(dirname $0)/..)"

echo "Run integration tests with cluster and registry creation"
echo "Source path: ${SOURCE_PATH}"
echo "Gardener kubeconfig path: ${GARDENER_KUBECONFIG_PATH}"
echo "Shoot cluster namespace: ${NAMESPACE}"
echo "Landscaper version: ${VERSION}"

TMP="${SOURCE_PATH}/tmp-int-test-cluster"
rm -f -r $TMP
mkdir -p $TMP
TARGET_SHOOT_DIR="${TMP}/target-shoot"
RESOURCE_SHOOT_DIR="${TMP}/resource-shoot"
mkdir -p $TARGET_SHOOT_DIR
mkdir -p $RESOURCE_SHOOT_DIR
echo "Config directory: ${TMP}"

"${SOURCE_PATH}/hack/int-test-helper/install-missing-software"

echo "Creating Target Shoot Cluster"
"${SOURCE_PATH}/hack/int-test-helper/create-shoot-cluster" $GARDENER_KUBECONFIG_PATH \
  $NAMESPACE \
  $TARGET_SHOOT_DIR \
  $MAX_NUM_CLUSTERS \
  $NUM_CLUSTERS_START_DELETE_OLDEST \
  $DURATION_FOR_CLUSTER_DELETION \
  $PR_ID \
  true \
  false \
  false \
  &>"${TARGET_SHOOT_DIR}/create-shoot-cluster.log" &

TARGET_SHOOT_CREATE_PID=$!

sleep 10

echo "Creating Resource Shoot Cluster"
"${SOURCE_PATH}/hack/int-test-helper/create-shoot-cluster" $GARDENER_KUBECONFIG_PATH \
  $NAMESPACE \
  $RESOURCE_SHOOT_DIR \
  $MAX_NUM_CLUSTERS \
  $NUM_CLUSTERS_START_DELETE_OLDEST \
  $DURATION_FOR_CLUSTER_DELETION \
  $PR_ID \
  false \
  true \
  true \
  &>"${RESOURCE_SHOOT_DIR}/create-shoot-cluster.log" &

RESOURCE_SHOOT_CREATE_PID=$!

if [[ $? != 0 ]]; then
  echo "Creating the shoot clusters failed"
  echo "###### TARGET SHOOT LOG ######"
  cat "${TARGET_SHOOT_DIR}/create-shoot-cluster.log"
  echo "###### RESOURCE SHOOT LOG ######"
  cat "${RESOURCE_SHOOT_DIR_SHOOT_DIR}/create-shoot-cluster.log"
fi

echo "Waiting until shoot clusters are ready"
wait $TARGET_SHOOT_CREATE_PID $RESOURCE_SHOOT_CREATE_PID

TARGET_SHOOT_KUBECONFIG_PATH="${TARGET_SHOOT_DIR}/kubeconfig.yaml"
RESOURCE_SHOOT_KUBECONFIG_PATH="${RESOURCE_SHOOT_DIR}/kubeconfig.yaml"

"${SOURCE_PATH}/hack/int-test-helper/create-registry" $TARGET_SHOOT_KUBECONFIG_PATH $TARGET_SHOOT_DIR

echo "Installing Landscaper"
"${SOURCE_PATH}/hack/int-test-helper/install-landscaper-dual" \
  -w $TARGET_SHOOT_DIR \
  -v $VERSION \
  -t $TARGET_SHOOT_KUBECONFIG_PATH \
  -r $RESOURCE_SHOOT_KUBECONFIG_PATH \
  -i "$(cat ${TARGET_SHOOT_DIR}/ingress-domain)"

"${SOURCE_PATH}/hack/int-test-helper/run-tests" $RESOURCE_SHOOT_KUBECONFIG_PATH ${TARGET_SHOOT_DIR}/docker.config $VERSION

"${SOURCE_PATH}/hack/int-test-helper/delete-shoot-cluster" $GARDENER_KUBECONFIG_PATH $NAMESPACE $TARGET_SHOOT_DIR
"${SOURCE_PATH}/hack/int-test-helper/delete-shoot-cluster" $GARDENER_KUBECONFIG_PATH $NAMESPACE $RESOURCE_SHOOT_DIR
