#!/bin/sh

# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

GARDENER_KUBECONFIG_PATH=$1
NAMESPACE=$2
VERSION=$3
PR_ID=$4

MAX_NUM_CLUSTERS=20
NUM_CLUSTERS_START_DELETE_OLDEST=15
DURATION_FOR_CLUSTER_DELETION=48h

SOURCE_PATH="$(realpath $(dirname $0)/..)"

echo "Run integration tests with cluster and registry creation"
echo "Source path: ${SOURCE_PATH}"
echo "Gardener kubeconfig path: ${GARDENER_KUBECONFIG_PATH}"
echo "Shoot cluster namespace: ${NAMESPACE}"
echo "Landscaper version: ${VERSION}"

TMP="${SOURCE_PATH}/tmp-int-test-cluster"
rm -f -r $TMP
mkdir -p $TMP
echo "Config directory: ${TMP}"

"${SOURCE_PATH}/hack/int-test-helper/install-missing-software"

TARGET_SHOOT_KUBECONFIG_PATH="${TMP}/target-shoot-kubeconfig.yaml"
RESOURCE_SHOOT_KUBECONFIG_PATH="${TMP}/resource-shoot-kubeconfig.yaml"

"${SOURCE_PATH}/hack/int-test-helper/create-shoot-cluster" $GARDENER_KUBECONFIG_PATH \
  $NAMESPACE \
  $TMP \
  $MAX_NUM_CLUSTERS \
  $NUM_CLUSTERS_START_DELETE_OLDEST \
  $DURATION_FOR_CLUSTER_DELETION \
  $PR_ID \
  true

cp "${TMP}/kubeconfig.yaml" "$TARGET_SHOOT_KUBECONFIG_PATH"

"${SOURCE_PATH}/hack/int-test-helper/create-shoot-cluster" $GARDENER_KUBECONFIG_PATH \
  $NAMESPACE \
  $TMP \
  $MAX_NUM_CLUSTERS \
  $NUM_CLUSTERS_START_DELETE_OLDEST \
  $DURATION_FOR_CLUSTER_DELETION \
  $PR_ID \
  false

cp "${TMP}/kubeconfig.yaml" "$RESOURCE_SHOOT_KUBECONFIG_PATH"

echo "Target cluster kubeconfig path: ${TARGET_SHOOT_KUBECONFIG_PATH}"
echo "Resource cluster kubeconfig path: ${RESOURCE_SHOOT_KUBECONFIG_PATH}"
echo "Ingress domain: $(cat ${TMP}/ingress-domain)"

"${SOURCE_PATH}/hack/int-test-helper/create-registry" $TARGET_SHOOT_KUBECONFIG_PATH $TMP
"${SOURCE_PATH}/hack/int-test-helper/install-landscaper-dual" \
  -w $TMP \
  -v $VERSION \
  -t $TARGET_SHOOT_KUBECONFIG_PATH \
  -r $RESOURCE_SHOOT_KUBECONFIG_PATH \
  -i "$(cat ${TMP}/ingress-domain)"

"${SOURCE_PATH}/hack/int-test-helper/run-tests" $RESOURCE_SHOOT_KUBECONFIG_PATH $TMP/docker.config $VERSION

mv "$TARGET_SHOOT_KUBECONFIG_PATH" "${TMP}/kubeconfig.yaml"
"${SOURCE_PATH}/hack/int-test-helper/delete-shoot-cluster" $GARDENER_KUBECONFIG_PATH $NAMESPACE $TMP

mv "$RESOURCE_SHOOT_KUBECONFIG_PATH" "${TMP}/kubeconfig.yaml"
"${SOURCE_PATH}/hack/int-test-helper/delete-shoot-cluster" $GARDENER_KUBECONFIG_PATH $NAMESPACE $TMP
