#!/bin/sh

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# Script executed in case of a PR. Currently this does nothing but it is planned to let it trigger the integration tests
# if the PR has some particular label.

set -o errexit
set -o nounset
set -o pipefail

echo "check if integration tests should be started"

if ! which git 1>/dev/null; then
  echo "Installing git... "
  apk add --no-cache --no-progress git
fi

SOURCE_PATH="$(dirname $0)/.."
cd "${SOURCE_PATH}"
SOURCE_PATH="$(pwd)"
export SOURCE_PATH

GIT_COMMENT=$(git show -s --format=%s)
echo "git comment: " $GIT_COMMENT

if git show -s --format=%s | grep run-int-tests; then
    echo "integration tests should be started"
    ./.ci/int-test
else
    echo "integration tests are skipped"
fi



