#!/bin/sh

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# Script executed in case of a commit to a PR. The script checks if the comment of the commit contains "run-int-tests".
# In that case, the integration tests are executed by calling ./.ci/int-test. The parameter $PR_ID is integrated in the
# test cluster name. The cluster name has the format it-pr$PR_ID-<4-digits>.

set -euo pipefail

PROJECT_ROOT="$(realpath $(dirname $0)/..)"
VERSION="$("$PROJECT_ROOT/hack/get-version.sh")"

export PROJECT_ROOT
export VERSION

echo "check if integration tests should be started"
(
  cd "$PROJECT_ROOT"
  PR_ID=$(git config -f "$PROJECT_ROOT/.git/config" pullrequest.id)
  echo "PR_ID: " $PR_ID
  export PR_ID

  GIT_COMMENT=$(git show -s --format=%s)
  echo "git comment: " $GIT_COMMENT

  if git show -s --format=%s | grep run-int-tests; then
      echo "integration tests should be started"
      "$PROJECT_ROOT/.ci/int-test" $PR_ID
  elif git branch --show-current | grep "renovate/"; then
       echo "Dependency update from renovate, integration tests should be started"
      "$PROJECT_ROOT/.ci/int-test" $PR_ID
   else
      echo "integration tests are skipped"
  fi
)
