#!/bin/bash

# SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

# Script executing the integration tests (without shoot cluster creation and deletion). It could be executed locally but
# is also called by the Gardener Concours jobs executing the integration tests.

# This script executes the following steps:
#
# - install-missing-software: Installs potentially missing software for the subsequent steps.
#
# - create-registry: Creates an OCI registry in a test shoot cluster. The kubeconfig for this cluster must be located
#   at the file path provided with $1.
#
# - install-landscaper: Installs the landscaper on the test shoot cluster. The landscaper version is provided by $2.
#
# - run-tests: Executes the integration tests on the test shoot cluster. The currently checkout state of the
#   integration tests is executed and not the state provided by the version in $2. $2 is only used in some integration tests
#   when a particular image is loaded.

set -o errexit
set -o nounset
set -o pipefail

KUBECONFIG_PATH=$1
VERSION=$2
SOURCE_PATH="$(dirname $0)/.."
cd "${SOURCE_PATH}"
SOURCE_PATH="$(pwd)"

echo "Run integration tests with registry creation"
echo "Source path: ${SOURCE_PATH}"
echo "Landscaper version: ${VERSION}"
echo "Test cluster kubeconfig path: ${KUBECONFIG_PATH}"

TMP="${SOURCE_PATH}/tmp-int-test-core"
rm -f -r $TMP
mkdir -p $TMP
echo "Config directory: ${TMP}"

./.ci/int-test-helper/install-missing-software
./.ci/int-test-helper/create-registry $KUBECONFIG_PATH $TMP
./.ci/int-test-helper/install-landscaper $KUBECONFIG_PATH ${VERSION} $TMP
./.ci/int-test-helper/run-tests $KUBECONFIG_PATH $TMP/docker.config ${VERSION}
