#!/bin/bash

# SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

KUBECONFIG_PATH=$1
VERSION=$2
SOURCE_PATH="$(dirname $0)/.."
cd "${SOURCE_PATH}"
SOURCE_PATH="$(pwd)"

echo "Run integration tests with registry creation"
echo "Source path: ${SOURCE_PATH}"
echo "Landscaper version: ${VERSION}"
echo "Test cluster kubeconfig path: ${KUBECONFIG_PATH}"

TMP="${SOURCE_PATH}/tmp-int-test"
rm -f -r $TMP
mkdir -p $TMP
echo "Config directory: ${TMP}"

./.ci/int-test-helper/create-registry $KUBECONFIG_PATH $TMP
./.ci/int-test-helper/install-missing-software
./.ci/int-test-helper/install-landscaper $KUBECONFIG_PATH $VERSION $TMP
./.ci/int-test-helper/run-tests $KUBECONFIG_PATH $TMP/docker.config $VERSION
