#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

PROJECT_ROOT="$(realpath $(dirname $0)/..)"

source "$PROJECT_ROOT/.ci/ensure-go"
"$PROJECT_ROOT/.ci/ensure-make"

apk add --no-cache git musl-dev curl
mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

# revert the version update in the gomod file
VERSION=$(cat ${PROJECT_ROOT}/VERSION)

# 0,/)/ only replaces the first ocurrence until the first dep block with ')' is reached
sed -i -e "0,/)/{s@github.com/gardener/landscaper/apis .*@github.com/gardener/landscaper/apis v0.0.0-00010101000000-000000000000@}" \
  ${PROJECT_ROOT}/go.mod

sed -i -e "0,/)/{s@github.com/gardener/landscaper/controller-utils .*@github.com/gardener/landscaper/controller-utils v0.0.0-00010101000000-000000000000@}" \
  ${PROJECT_ROOT}/go.mod

sed -i -e "0,/)/{s@github.com/gardener/landscaper/apis .*@github.com/gardener/landscaper/apis v0.0.0-00010101000000-000000000000@}" \
  ${PROJECT_ROOT}/controller-utils/go.mod

(
  cd $PROJECT_ROOT
  make revendor
)
