#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

SOURCE_PATH="$(dirname $0)/.."

$SOURCE_PATH/hack/create-helm-chart.sh eu.gcr.io/gardener-project/landscaper/charts/landscaper-controller charts/landscaper
$SOURCE_PATH/hack/create-helm-chart.sh eu.gcr.io/gardener-project/landscaper/charts/container-deployer-controller charts/container-deployer
