#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

echo "Landscaper release: starting .ci/release"

SOURCE_DIR="$(dirname $0)/.."

apk add --no-cache git make musl-dev curl gcompat
GO_VERSION=$(grep "go [0-9].[0-9][0-9]" ${SOURCE_DIR}/go.mod| sed 's/ //g')
curl -LO https://golang.org/dl/${GO_VERSION}.linux-amd64.tar.gz
tar -C /usr/local -xzf ${GO_VERSION}.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

echo "Landscaper release: updating go.mod files"

# update go.mod's internal dependency to local module so that it can be used by other repositories
VERSION=$(cat ${SOURCE_DIR}/VERSION)

# 0,/)/ only replaces the first ocurrence until the first dep block with ')' is reached
sed -i -e "0,/)/{s@github.com/gardener/landscaper/apis .*@github.com/gardener/landscaper/apis ${VERSION}@}" \
  ${SOURCE_DIR}/go.mod

sed -i -e "0,/)/{s@github.com/gardener/landscaper/controller-utils .*@github.com/gardener/landscaper/controller-utils ${VERSION}@}" \
  ${SOURCE_DIR}/go.mod

sed -i -e "0,/)/{s@github.com/gardener/landscaper/apis .*@github.com/gardener/landscaper/apis ${VERSION}@}" \
  ${SOURCE_DIR}/controller-utils/go.mod

echo "Landscaper release: starting revendor"

cd $SOURCE_DIR
make revendor

echo "Landscaper release: finished revendor"

# the helm chart versions need to be updated in the release step to reflect the change in the Git repository
${SOURCE_DIR}/hack/update-helm-chart-version.sh

echo "Landscaper release: finished .ci/release"
