#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

apk add --no-cache git make musl-dev curl
curl -LO https://golang.org/dl/go1.19.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.19.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

SOURCE_DIR="$(dirname $0)/.."

# update go.mod's internal dependency to local module so that it can be used by other repositories
VERSION=$(cat ${SOURCE_DIR}/VERSION)

# 0,/)/ only replaces the first ocurrence until the first dep block with ')' is reached
sed -i -e "0,/)/{s@github.com/gardener/landscaper/apis .*@github.com/gardener/landscaper/apis ${VERSION}@}" \
  ${SOURCE_DIR}/go.mod

sed -i -e "0,/)/{s@github.com/gardener/landscaper/controller-utils .*@github.com/gardener/landscaper/controller-utils ${VERSION}@}" \
  ${SOURCE_DIR}/go.mod

sed -i -e "0,/)/{s@github.com/gardener/landscaper/apis .*@github.com/gardener/landscaper/apis ${VERSION}@}" \
  ${SOURCE_DIR}/controller-utils/go.mod

cd $SOURCE_DIR
make revendor

# the helm chart versions need to be updated in the release step to reflect the change in the Git repository
${SOURCE_DIR}/hack/update-helm-chart-version.sh
