#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

echo "TODO: disabled for now"
exit 0

PROJECT_ROOT="$(realpath $(dirname $0)/..)"

(
  cd "${PROJECT_ROOT}"

  make revendor
  SKIP_FORMATTING_CHECK=true SKIP_DOCS_INDEX_CHECK=true make verify # code formatting and docs index generation happens during head-update pipeline step, no need to verify it here
  make test
)
