#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

cd "$(dirname $0)/.."

make install-requirements

mkdir -p /go/src/github.com/gardener/landscaper
cp -r . /go/src/github.com/gardener/landscaper
cd /go/src/github.com/gardener/landscaper

make verify
make test
