# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: root-2
spec:
  blueprintRef: root-a:1.0.0

  imports:
  - from: exp-a
    to: imp-a

  exports:
  - from: exp-a
    to: exp-b