apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Target
metadata:
  name: minikube-from-host
  namespace: default
spec:
  type: landscaper.gardener.cloud/kubernetes-cluster
  config:
    kubeconfig: |
