# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: landscaper.gardener.cloud/v1alpha1
kind: DeployItem
metadata:
  name: my-component-definition
spec:

  type: container | helm | manifest

  target: # optional
    name: abc

  context: "default"

  config:
    apiVersion: mydeplyoer/v1
    kind: ProviderConfiguration
    ...

status:
  phase: Succeeded
  observedGeneration: 0
