# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: my-ingress
  annotations:
    # this annotation is required such that the installation is picked up by the Landscaper
    # it will be removed when processing has started
    landscaper.gardener.cloud/operation: reconcile
spec:
  componentDescriptor:
    ref:
      repositoryContext:
        type: ociRegistry
        baseUrl: eu.gcr.io/gardener-project/landscaper/tutorials/components
      componentName: github.com/gardener/landscaper/local/ingress-nginx
      version: v0.3.3
  blueprint:
    ref:
      resourceName: ingress-nginx-blueprint

  imports:
    targets:
    - name: cluster
      target: "my-cluster"
    data:
    - name: namespace
      configMapRef:
        key: "namespace"
        name: "my-imports" # name of the configmap;

  exports:
    data:
    - name: ingressClass
      dataRef: "myIngressClass"