# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

name: root-a
version: 1.0.0

imports:
- name: imp-a
  schema:
    type: string

exports:
- name: exp-a
  schema:
    type: string

deployExecutions:
- type: GoTemplate
  template: |
    deployItems:
    - name: main
      type: landscaper.gardener.cloud/mock
      config:
        apiVersion: mock.deployer.landscaper.gardener.cloud/v1alpha1
        kind: ProviderConfiguration
        providerStatus:
          apiVersion: mock.deployer.landscaper.gardener.cloud/v1alpha1
          kind: ProviderStatus
          imp: {{ index .imports "imp-a" }}
        export:
          exp-a: exp-mock

exportExecutions:
- type: GoTemplate
  template: |
    exports:
      exp-a: {{ index .values.deployitems.main "exp-a" }}
