apiVersion: landscaper.gardener.cloud/v1alpha1
kind: InstallationTemplate
name: subinst3
blueprint:
  ref: cd://resources/blueprint-sub

imports:
  targets:
    - name: cluster
      target: cluster

  data:
    - name: configmap-name-in
      dataRef: configmap-name-3

exports:
  data:
    - name: configmap-name-out
      dataRef: configmap-name-4
