apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: manifest-demo
  namespace: example
  annotations:
    landscaper.gardener.cloud/operation: reconcile

spec:
  blueprint:
    ref:
      resourceName: blueprint

  componentDescriptor:
    ref:
      componentName: test.net/test
      repositoryContext:
        baseUrl: <OCIURL>
        type: ociRegistry
      version: v0.1.0

  imports:
    targets:
      - name: cluster
        target: '#my-cluster'
