apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: example
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: helloworld
        image: <IMAGEURL>
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: myregistrykey 