// +build !ignore_autogenerated

/*
Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	json "encoding/json"
	unsafe "unsafe"

	core "github.com/gardener/landscaper/pkg/apis/core"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Component)(nil), (*core.Component)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Component_To_core_Component(a.(*Component), b.(*core.Component), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Component)(nil), (*Component)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Component_To_v1alpha1_Component(a.(*core.Component), b.(*Component), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentDefinition)(nil), (*core.ComponentDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentDefinition_To_core_ComponentDefinition(a.(*ComponentDefinition), b.(*core.ComponentDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ComponentDefinition)(nil), (*ComponentDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ComponentDefinition_To_v1alpha1_ComponentDefinition(a.(*core.ComponentDefinition), b.(*ComponentDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentDefinitionList)(nil), (*core.ComponentDefinitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentDefinitionList_To_core_ComponentDefinitionList(a.(*ComponentDefinitionList), b.(*core.ComponentDefinitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ComponentDefinitionList)(nil), (*ComponentDefinitionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ComponentDefinitionList_To_v1alpha1_ComponentDefinitionList(a.(*core.ComponentDefinitionList), b.(*ComponentDefinitionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentList)(nil), (*core.ComponentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentList_To_core_ComponentList(a.(*ComponentList), b.(*core.ComponentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ComponentList)(nil), (*ComponentList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ComponentList_To_v1alpha1_ComponentList(a.(*core.ComponentList), b.(*ComponentList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentSpec)(nil), (*core.ComponentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentSpec_To_core_ComponentSpec(a.(*ComponentSpec), b.(*core.ComponentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ComponentSpec)(nil), (*ComponentSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ComponentSpec_To_v1alpha1_ComponentSpec(a.(*core.ComponentSpec), b.(*ComponentSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentStatus)(nil), (*core.ComponentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentStatus_To_core_ComponentStatus(a.(*ComponentStatus), b.(*core.ComponentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ComponentStatus)(nil), (*ComponentStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ComponentStatus_To_v1alpha1_ComponentStatus(a.(*core.ComponentStatus), b.(*ComponentStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ContainerConfig)(nil), (*core.ContainerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ContainerConfig_To_core_ContainerConfig(a.(*ContainerConfig), b.(*core.ContainerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ContainerConfig)(nil), (*ContainerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ContainerConfig_To_v1alpha1_ContainerConfig(a.(*core.ContainerConfig), b.(*ContainerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CustomType)(nil), (*core.CustomType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CustomType_To_core_CustomType(a.(*CustomType), b.(*core.CustomType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.CustomType)(nil), (*CustomType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_CustomType_To_v1alpha1_CustomType(a.(*core.CustomType), b.(*CustomType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Default)(nil), (*core.Default)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Default_To_core_Default(a.(*Default), b.(*core.Default), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Default)(nil), (*Default)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Default_To_v1alpha1_Default(a.(*core.Default), b.(*Default), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DefinitionSpec)(nil), (*core.DefinitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DefinitionSpec_To_core_DefinitionSpec(a.(*DefinitionSpec), b.(*core.DefinitionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DefinitionSpec)(nil), (*DefinitionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DefinitionSpec_To_v1alpha1_DefinitionSpec(a.(*core.DefinitionSpec), b.(*DefinitionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DefinitionStatus)(nil), (*core.DefinitionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DefinitionStatus_To_core_DefinitionStatus(a.(*DefinitionStatus), b.(*core.DefinitionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DefinitionStatus)(nil), (*DefinitionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DefinitionStatus_To_v1alpha1_DefinitionStatus(a.(*core.DefinitionStatus), b.(*DefinitionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DefinitionTypeCondition)(nil), (*core.DefinitionTypeCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DefinitionTypeCondition_To_core_DefinitionTypeCondition(a.(*DefinitionTypeCondition), b.(*core.DefinitionTypeCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DefinitionTypeCondition)(nil), (*DefinitionTypeCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DefinitionTypeCondition_To_v1alpha1_DefinitionTypeCondition(a.(*core.DefinitionTypeCondition), b.(*DefinitionTypeCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Execution)(nil), (*core.Executor)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Executor_To_core_Executor(a.(*Execution), b.(*core.Executor), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Executor)(nil), (*Execution)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Executor_To_v1alpha1_Executor(a.(*core.Executor), b.(*Execution), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExecutorState)(nil), (*ExecutorState)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExecutorState_To_v1alpha1_ExecutorState(a.(*ExecutorState), b.(*ExecutorState), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExecutorState)(nil), (*ExecutorState)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExecutorState_To_v1alpha1_ExecutorState(a.(*ExecutorState), b.(*ExecutorState), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Export)(nil), (*core.Export)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Export_To_core_Export(a.(*Export), b.(*core.Export), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Export)(nil), (*Export)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Export_To_v1alpha1_Export(a.(*core.Export), b.(*Export), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExportStatus)(nil), (*core.ExportStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExportStatus_To_core_ExportStatus(a.(*ExportStatus), b.(*core.ExportStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ExportStatus)(nil), (*ExportStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ExportStatus_To_v1alpha1_ExportStatus(a.(*core.ExportStatus), b.(*ExportStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Import)(nil), (*core.Import)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Import_To_core_Import(a.(*Import), b.(*core.Import), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Import)(nil), (*Import)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Import_To_v1alpha1_Import(a.(*core.Import), b.(*Import), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LandscapeConfiguration)(nil), (*core.LandscapeConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LandscapeConfiguration_To_core_LandscapeConfiguration(a.(*LandscapeConfiguration), b.(*core.LandscapeConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.LandscapeConfiguration)(nil), (*LandscapeConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_LandscapeConfiguration_To_v1alpha1_LandscapeConfiguration(a.(*core.LandscapeConfiguration), b.(*LandscapeConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LandscapeConfigurationList)(nil), (*core.LandscapeConfigurationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LandscapeConfigurationList_To_core_LandscapeConfigurationList(a.(*LandscapeConfigurationList), b.(*core.LandscapeConfigurationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.LandscapeConfigurationList)(nil), (*LandscapeConfigurationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_LandscapeConfigurationList_To_v1alpha1_LandscapeConfigurationList(a.(*core.LandscapeConfigurationList), b.(*LandscapeConfigurationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LandscapeConfigurationSpec)(nil), (*core.LandscapeConfigurationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LandscapeConfigurationSpec_To_core_LandscapeConfigurationSpec(a.(*LandscapeConfigurationSpec), b.(*core.LandscapeConfigurationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.LandscapeConfigurationSpec)(nil), (*LandscapeConfigurationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_LandscapeConfigurationSpec_To_v1alpha1_LandscapeConfigurationSpec(a.(*core.LandscapeConfigurationSpec), b.(*LandscapeConfigurationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespacedName)(nil), (*core.NamespacedName)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NamespacedName_To_core_NamespacedName(a.(*NamespacedName), b.(*core.NamespacedName), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.NamespacedName)(nil), (*NamespacedName)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_NamespacedName_To_v1alpha1_NamespacedName(a.(*core.NamespacedName), b.(*NamespacedName), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ScriptConfig)(nil), (*core.ScriptConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ScriptConfig_To_core_ScriptConfig(a.(*ScriptConfig), b.(*core.ScriptConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ScriptConfig)(nil), (*ScriptConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ScriptConfig_To_v1alpha1_ScriptConfig(a.(*core.ScriptConfig), b.(*ScriptConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TemplateConfig)(nil), (*core.TemplateConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TemplateConfig_To_core_TemplateConfig(a.(*TemplateConfig), b.(*core.TemplateConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TemplateConfig)(nil), (*TemplateConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TemplateConfig_To_v1alpha1_TemplateConfig(a.(*core.TemplateConfig), b.(*TemplateConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Type)(nil), (*core.Type)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Type_To_core_Type(a.(*Type), b.(*core.Type), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Type)(nil), (*Type)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Type_To_v1alpha1_Type(a.(*core.Type), b.(*Type), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TypeCondition)(nil), (*core.TypeCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TypeCondition_To_core_TypeCondition(a.(*TypeCondition), b.(*core.TypeCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TypeCondition)(nil), (*TypeCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TypeCondition_To_v1alpha1_TypeCondition(a.(*core.TypeCondition), b.(*TypeCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TypeList)(nil), (*core.TypeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TypeList_To_core_TypeList(a.(*TypeList), b.(*core.TypeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TypeList)(nil), (*TypeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TypeList_To_v1alpha1_TypeList(a.(*core.TypeList), b.(*TypeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TypeSpec)(nil), (*core.TypeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TypeSpec_To_core_TypeSpec(a.(*TypeSpec), b.(*core.TypeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TypeSpec)(nil), (*TypeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TypeSpec_To_v1alpha1_TypeSpec(a.(*core.TypeSpec), b.(*TypeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TypeStatus)(nil), (*core.TypeStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TypeStatus_To_core_TypeStatus(a.(*TypeStatus), b.(*core.TypeStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.TypeStatus)(nil), (*TypeStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_TypeStatus_To_v1alpha1_TypeStatus(a.(*core.TypeStatus), b.(*TypeStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Component_To_core_Component(in *Component, out *core.Component, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ComponentSpec_To_core_ComponentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ComponentStatus_To_core_ComponentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Component_To_core_Component is an autogenerated conversion function.
func Convert_v1alpha1_Component_To_core_Component(in *Component, out *core.Component, s conversion.Scope) error {
	return autoConvert_v1alpha1_Component_To_core_Component(in, out, s)
}

func autoConvert_core_Component_To_v1alpha1_Component(in *core.Component, out *Component, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_ComponentSpec_To_v1alpha1_ComponentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_core_ComponentStatus_To_v1alpha1_ComponentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_Component_To_v1alpha1_Component is an autogenerated conversion function.
func Convert_core_Component_To_v1alpha1_Component(in *core.Component, out *Component, s conversion.Scope) error {
	return autoConvert_core_Component_To_v1alpha1_Component(in, out, s)
}

func autoConvert_v1alpha1_ComponentDefinition_To_core_ComponentDefinition(in *ComponentDefinition, out *core.ComponentDefinition, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DefinitionSpec_To_core_DefinitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DefinitionStatus_To_core_DefinitionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ComponentDefinition_To_core_ComponentDefinition is an autogenerated conversion function.
func Convert_v1alpha1_ComponentDefinition_To_core_ComponentDefinition(in *ComponentDefinition, out *core.ComponentDefinition, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentDefinition_To_core_ComponentDefinition(in, out, s)
}

func autoConvert_core_ComponentDefinition_To_v1alpha1_ComponentDefinition(in *core.ComponentDefinition, out *ComponentDefinition, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_DefinitionSpec_To_v1alpha1_DefinitionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_core_DefinitionStatus_To_v1alpha1_DefinitionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_ComponentDefinition_To_v1alpha1_ComponentDefinition is an autogenerated conversion function.
func Convert_core_ComponentDefinition_To_v1alpha1_ComponentDefinition(in *core.ComponentDefinition, out *ComponentDefinition, s conversion.Scope) error {
	return autoConvert_core_ComponentDefinition_To_v1alpha1_ComponentDefinition(in, out, s)
}

func autoConvert_v1alpha1_ComponentDefinitionList_To_core_ComponentDefinitionList(in *ComponentDefinitionList, out *core.ComponentDefinitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.ComponentDefinition)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ComponentDefinitionList_To_core_ComponentDefinitionList is an autogenerated conversion function.
func Convert_v1alpha1_ComponentDefinitionList_To_core_ComponentDefinitionList(in *ComponentDefinitionList, out *core.ComponentDefinitionList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentDefinitionList_To_core_ComponentDefinitionList(in, out, s)
}

func autoConvert_core_ComponentDefinitionList_To_v1alpha1_ComponentDefinitionList(in *core.ComponentDefinitionList, out *ComponentDefinitionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ComponentDefinition)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_ComponentDefinitionList_To_v1alpha1_ComponentDefinitionList is an autogenerated conversion function.
func Convert_core_ComponentDefinitionList_To_v1alpha1_ComponentDefinitionList(in *core.ComponentDefinitionList, out *ComponentDefinitionList, s conversion.Scope) error {
	return autoConvert_core_ComponentDefinitionList_To_v1alpha1_ComponentDefinitionList(in, out, s)
}

func autoConvert_v1alpha1_ComponentList_To_core_ComponentList(in *ComponentList, out *core.ComponentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]core.Component, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Component_To_core_Component(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ComponentList_To_core_ComponentList is an autogenerated conversion function.
func Convert_v1alpha1_ComponentList_To_core_ComponentList(in *ComponentList, out *core.ComponentList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentList_To_core_ComponentList(in, out, s)
}

func autoConvert_core_ComponentList_To_v1alpha1_ComponentList(in *core.ComponentList, out *ComponentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Component, len(*in))
		for i := range *in {
			if err := Convert_core_Component_To_v1alpha1_Component(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_core_ComponentList_To_v1alpha1_ComponentList is an autogenerated conversion function.
func Convert_core_ComponentList_To_v1alpha1_ComponentList(in *core.ComponentList, out *ComponentList, s conversion.Scope) error {
	return autoConvert_core_ComponentList_To_v1alpha1_ComponentList(in, out, s)
}

func autoConvert_v1alpha1_ComponentSpec_To_core_ComponentSpec(in *ComponentSpec, out *core.ComponentSpec, s conversion.Scope) error {
	out.DefinitionRef = in.DefinitionRef
	out.Imports = *(*[]core.Import)(unsafe.Pointer(&in.Imports))
	out.Exports = *(*[]core.Export)(unsafe.Pointer(&in.Exports))
	return nil
}

// Convert_v1alpha1_ComponentSpec_To_core_ComponentSpec is an autogenerated conversion function.
func Convert_v1alpha1_ComponentSpec_To_core_ComponentSpec(in *ComponentSpec, out *core.ComponentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentSpec_To_core_ComponentSpec(in, out, s)
}

func autoConvert_core_ComponentSpec_To_v1alpha1_ComponentSpec(in *core.ComponentSpec, out *ComponentSpec, s conversion.Scope) error {
	out.DefinitionRef = in.DefinitionRef
	out.Imports = *(*[]Import)(unsafe.Pointer(&in.Imports))
	out.Exports = *(*[]Export)(unsafe.Pointer(&in.Exports))
	return nil
}

// Convert_core_ComponentSpec_To_v1alpha1_ComponentSpec is an autogenerated conversion function.
func Convert_core_ComponentSpec_To_v1alpha1_ComponentSpec(in *core.ComponentSpec, out *ComponentSpec, s conversion.Scope) error {
	return autoConvert_core_ComponentSpec_To_v1alpha1_ComponentSpec(in, out, s)
}

func autoConvert_v1alpha1_ComponentStatus_To_core_ComponentStatus(in *ComponentStatus, out *core.ComponentStatus, s conversion.Scope) error {
	out.Phase = core.ComponentPhase(in.Phase)
	// WARNING: in.Executors requires manual conversion: does not exist in peer-type
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]core.Export, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_ExportStatus_To_core_Export(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Exports = nil
	}
	return nil
}

func autoConvert_core_ComponentStatus_To_v1alpha1_ComponentStatus(in *core.ComponentStatus, out *ComponentStatus, s conversion.Scope) error {
	out.Phase = ComponentPhase(in.Phase)
	if in.Exports != nil {
		in, out := &in.Exports, &out.Exports
		*out = make([]ExportStatus, len(*in))
		for i := range *in {
			if err := Convert_core_Export_To_v1alpha1_ExportStatus(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Exports = nil
	}
	return nil
}

// Convert_core_ComponentStatus_To_v1alpha1_ComponentStatus is an autogenerated conversion function.
func Convert_core_ComponentStatus_To_v1alpha1_ComponentStatus(in *core.ComponentStatus, out *ComponentStatus, s conversion.Scope) error {
	return autoConvert_core_ComponentStatus_To_v1alpha1_ComponentStatus(in, out, s)
}

func autoConvert_v1alpha1_ContainerConfig_To_core_ContainerConfig(in *ContainerConfig, out *core.ContainerConfig, s conversion.Scope) error {
	out.Image = in.Image
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	out.Args = *(*[]string)(unsafe.Pointer(&in.Args))
	out.WorkingDir = in.WorkingDir
	return nil
}

// Convert_v1alpha1_ContainerConfig_To_core_ContainerConfig is an autogenerated conversion function.
func Convert_v1alpha1_ContainerConfig_To_core_ContainerConfig(in *ContainerConfig, out *core.ContainerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ContainerConfig_To_core_ContainerConfig(in, out, s)
}

func autoConvert_core_ContainerConfig_To_v1alpha1_ContainerConfig(in *core.ContainerConfig, out *ContainerConfig, s conversion.Scope) error {
	out.Image = in.Image
	out.Command = *(*[]string)(unsafe.Pointer(&in.Command))
	out.Args = *(*[]string)(unsafe.Pointer(&in.Args))
	out.WorkingDir = in.WorkingDir
	return nil
}

// Convert_core_ContainerConfig_To_v1alpha1_ContainerConfig is an autogenerated conversion function.
func Convert_core_ContainerConfig_To_v1alpha1_ContainerConfig(in *core.ContainerConfig, out *ContainerConfig, s conversion.Scope) error {
	return autoConvert_core_ContainerConfig_To_v1alpha1_ContainerConfig(in, out, s)
}

func autoConvert_v1alpha1_CustomType_To_core_CustomType(in *CustomType, out *core.CustomType, s conversion.Scope) error {
	out.Name = in.Name
	out.OpenAPIV3Schema = in.OpenAPIV3Schema
	return nil
}

// Convert_v1alpha1_CustomType_To_core_CustomType is an autogenerated conversion function.
func Convert_v1alpha1_CustomType_To_core_CustomType(in *CustomType, out *core.CustomType, s conversion.Scope) error {
	return autoConvert_v1alpha1_CustomType_To_core_CustomType(in, out, s)
}

func autoConvert_core_CustomType_To_v1alpha1_CustomType(in *core.CustomType, out *CustomType, s conversion.Scope) error {
	out.Name = in.Name
	out.OpenAPIV3Schema = in.OpenAPIV3Schema
	return nil
}

// Convert_core_CustomType_To_v1alpha1_CustomType is an autogenerated conversion function.
func Convert_core_CustomType_To_v1alpha1_CustomType(in *core.CustomType, out *CustomType, s conversion.Scope) error {
	return autoConvert_core_CustomType_To_v1alpha1_CustomType(in, out, s)
}

func autoConvert_v1alpha1_Default_To_core_Default(in *Default, out *core.Default, s conversion.Scope) error {
	out.Value = *(*json.RawMessage)(unsafe.Pointer(&in.Value))
	out.Reference = in.Reference
	return nil
}

// Convert_v1alpha1_Default_To_core_Default is an autogenerated conversion function.
func Convert_v1alpha1_Default_To_core_Default(in *Default, out *core.Default, s conversion.Scope) error {
	return autoConvert_v1alpha1_Default_To_core_Default(in, out, s)
}

func autoConvert_core_Default_To_v1alpha1_Default(in *core.Default, out *Default, s conversion.Scope) error {
	out.Value = *(*json.RawMessage)(unsafe.Pointer(&in.Value))
	out.Reference = in.Reference
	return nil
}

// Convert_core_Default_To_v1alpha1_Default is an autogenerated conversion function.
func Convert_core_Default_To_v1alpha1_Default(in *core.Default, out *Default, s conversion.Scope) error {
	return autoConvert_core_Default_To_v1alpha1_Default(in, out, s)
}

func autoConvert_v1alpha1_DefinitionSpec_To_core_DefinitionSpec(in *DefinitionSpec, out *core.DefinitionSpec, s conversion.Scope) error {
	out.CustomTypes = *(*[]core.CustomType)(unsafe.Pointer(&in.CustomTypes))
	out.Import = *(*json.RawMessage)(unsafe.Pointer(&in.Import))
	out.Export = *(*json.RawMessage)(unsafe.Pointer(&in.Export))
	out.Executors = *(*[]core.Executor)(unsafe.Pointer(&in.Executors))
	return nil
}

// Convert_v1alpha1_DefinitionSpec_To_core_DefinitionSpec is an autogenerated conversion function.
func Convert_v1alpha1_DefinitionSpec_To_core_DefinitionSpec(in *DefinitionSpec, out *core.DefinitionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DefinitionSpec_To_core_DefinitionSpec(in, out, s)
}

func autoConvert_core_DefinitionSpec_To_v1alpha1_DefinitionSpec(in *core.DefinitionSpec, out *DefinitionSpec, s conversion.Scope) error {
	out.CustomTypes = *(*[]CustomType)(unsafe.Pointer(&in.CustomTypes))
	out.Import = *(*json.RawMessage)(unsafe.Pointer(&in.Import))
	out.Export = *(*json.RawMessage)(unsafe.Pointer(&in.Export))
	out.Executors = *(*[]Execution)(unsafe.Pointer(&in.Executors))
	return nil
}

// Convert_core_DefinitionSpec_To_v1alpha1_DefinitionSpec is an autogenerated conversion function.
func Convert_core_DefinitionSpec_To_v1alpha1_DefinitionSpec(in *core.DefinitionSpec, out *DefinitionSpec, s conversion.Scope) error {
	return autoConvert_core_DefinitionSpec_To_v1alpha1_DefinitionSpec(in, out, s)
}

func autoConvert_v1alpha1_DefinitionStatus_To_core_DefinitionStatus(in *DefinitionStatus, out *core.DefinitionStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.TypeConditions = *(*[]core.DefinitionTypeCondition)(unsafe.Pointer(&in.TypeConditions))
	return nil
}

// Convert_v1alpha1_DefinitionStatus_To_core_DefinitionStatus is an autogenerated conversion function.
func Convert_v1alpha1_DefinitionStatus_To_core_DefinitionStatus(in *DefinitionStatus, out *core.DefinitionStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_DefinitionStatus_To_core_DefinitionStatus(in, out, s)
}

func autoConvert_core_DefinitionStatus_To_v1alpha1_DefinitionStatus(in *core.DefinitionStatus, out *DefinitionStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.TypeConditions = *(*[]DefinitionTypeCondition)(unsafe.Pointer(&in.TypeConditions))
	return nil
}

// Convert_core_DefinitionStatus_To_v1alpha1_DefinitionStatus is an autogenerated conversion function.
func Convert_core_DefinitionStatus_To_v1alpha1_DefinitionStatus(in *core.DefinitionStatus, out *DefinitionStatus, s conversion.Scope) error {
	return autoConvert_core_DefinitionStatus_To_v1alpha1_DefinitionStatus(in, out, s)
}

func autoConvert_v1alpha1_DefinitionTypeCondition_To_core_DefinitionTypeCondition(in *DefinitionTypeCondition, out *core.DefinitionTypeCondition, s conversion.Scope) error {
	out.TypeName = in.TypeName
	if err := Convert_v1alpha1_TypeCondition_To_core_TypeCondition(&in.TypeCondition, &out.TypeCondition, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_DefinitionTypeCondition_To_core_DefinitionTypeCondition is an autogenerated conversion function.
func Convert_v1alpha1_DefinitionTypeCondition_To_core_DefinitionTypeCondition(in *DefinitionTypeCondition, out *core.DefinitionTypeCondition, s conversion.Scope) error {
	return autoConvert_v1alpha1_DefinitionTypeCondition_To_core_DefinitionTypeCondition(in, out, s)
}

func autoConvert_core_DefinitionTypeCondition_To_v1alpha1_DefinitionTypeCondition(in *core.DefinitionTypeCondition, out *DefinitionTypeCondition, s conversion.Scope) error {
	out.TypeName = in.TypeName
	if err := Convert_core_TypeCondition_To_v1alpha1_TypeCondition(&in.TypeCondition, &out.TypeCondition, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_DefinitionTypeCondition_To_v1alpha1_DefinitionTypeCondition is an autogenerated conversion function.
func Convert_core_DefinitionTypeCondition_To_v1alpha1_DefinitionTypeCondition(in *core.DefinitionTypeCondition, out *DefinitionTypeCondition, s conversion.Scope) error {
	return autoConvert_core_DefinitionTypeCondition_To_v1alpha1_DefinitionTypeCondition(in, out, s)
}

func autoConvert_v1alpha1_Executor_To_core_Executor(in *Execution, out *core.Executor, s conversion.Scope) error {
	out.Type = core.ExecutorType(in.Type)
	out.ContainerConfig = (*core.ContainerConfig)(unsafe.Pointer(in.ContainerConfig))
	out.ScriptConfig = (*core.ScriptConfig)(unsafe.Pointer(in.ScriptConfig))
	return nil
}

// Convert_v1alpha1_Executor_To_core_Executor is an autogenerated conversion function.
func Convert_v1alpha1_Executor_To_core_Executor(in *Execution, out *core.Executor, s conversion.Scope) error {
	return autoConvert_v1alpha1_Executor_To_core_Executor(in, out, s)
}

func autoConvert_core_Executor_To_v1alpha1_Executor(in *core.Executor, out *Execution, s conversion.Scope) error {
	out.Type = ExecutionType(in.Type)
	out.ContainerConfig = (*ContainerConfig)(unsafe.Pointer(in.ContainerConfig))
	out.ScriptConfig = (*ScriptConfig)(unsafe.Pointer(in.ScriptConfig))
	return nil
}

// Convert_core_Executor_To_v1alpha1_Executor is an autogenerated conversion function.
func Convert_core_Executor_To_v1alpha1_Executor(in *core.Executor, out *Execution, s conversion.Scope) error {
	return autoConvert_core_Executor_To_v1alpha1_Executor(in, out, s)
}

func autoConvert_v1alpha1_ExecutorState_To_v1alpha1_ExecutorState(in *ExecutorState, out *ExecutorState, s conversion.Scope) error {
	out.Phase = ComponentPhase(in.Phase)
	return nil
}

// Convert_v1alpha1_ExecutorState_To_v1alpha1_ExecutorState is an autogenerated conversion function.
func Convert_v1alpha1_ExecutorState_To_v1alpha1_ExecutorState(in *ExecutorState, out *ExecutorState, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExecutorState_To_v1alpha1_ExecutorState(in, out, s)
}

func autoConvert_v1alpha1_ExecutorState_To_v1alpha1_ExecutorState(in *ExecutorState, out *ExecutorState, s conversion.Scope) error {
	out.Phase = ComponentPhase(in.Phase)
	return nil
}

// Convert_v1alpha1_ExecutorState_To_v1alpha1_ExecutorState is an autogenerated conversion function.
func Convert_v1alpha1_ExecutorState_To_v1alpha1_ExecutorState(in *ExecutorState, out *ExecutorState, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExecutorState_To_v1alpha1_ExecutorState(in, out, s)
}

func autoConvert_v1alpha1_Export_To_core_Export(in *Export, out *core.Export, s conversion.Scope) error {
	out.From = in.From
	out.To = in.To
	out.Type = in.Type
	return nil
}

// Convert_v1alpha1_Export_To_core_Export is an autogenerated conversion function.
func Convert_v1alpha1_Export_To_core_Export(in *Export, out *core.Export, s conversion.Scope) error {
	return autoConvert_v1alpha1_Export_To_core_Export(in, out, s)
}

func autoConvert_core_Export_To_v1alpha1_Export(in *core.Export, out *Export, s conversion.Scope) error {
	out.From = in.From
	out.To = in.To
	out.Type = in.Type
	return nil
}

// Convert_core_Export_To_v1alpha1_Export is an autogenerated conversion function.
func Convert_core_Export_To_v1alpha1_Export(in *core.Export, out *Export, s conversion.Scope) error {
	return autoConvert_core_Export_To_v1alpha1_Export(in, out, s)
}

func autoConvert_v1alpha1_ExportStatus_To_core_ExportStatus(in *ExportStatus, out *core.ExportStatus, s conversion.Scope) error {
	out.To = in.To
	out.Type = in.Type
	out.Generation = in.Generation
	out.Value = *(*json.RawMessage)(unsafe.Pointer(&in.Value))
	return nil
}

// Convert_v1alpha1_ExportStatus_To_core_ExportStatus is an autogenerated conversion function.
func Convert_v1alpha1_ExportStatus_To_core_ExportStatus(in *ExportStatus, out *core.ExportStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExportStatus_To_core_ExportStatus(in, out, s)
}

func autoConvert_core_ExportStatus_To_v1alpha1_ExportStatus(in *core.ExportStatus, out *ExportStatus, s conversion.Scope) error {
	out.To = in.To
	out.Type = in.Type
	out.Generation = in.Generation
	out.Value = *(*json.RawMessage)(unsafe.Pointer(&in.Value))
	return nil
}

// Convert_core_ExportStatus_To_v1alpha1_ExportStatus is an autogenerated conversion function.
func Convert_core_ExportStatus_To_v1alpha1_ExportStatus(in *core.ExportStatus, out *ExportStatus, s conversion.Scope) error {
	return autoConvert_core_ExportStatus_To_v1alpha1_ExportStatus(in, out, s)
}

func autoConvert_v1alpha1_Import_To_core_Import(in *Import, out *core.Import, s conversion.Scope) error {
	out.From = in.From
	out.To = in.To
	out.Type = in.Type
	out.Required = in.Required
	if err := Convert_v1alpha1_Default_To_core_Default(&in.Default, &out.Default, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Import_To_core_Import is an autogenerated conversion function.
func Convert_v1alpha1_Import_To_core_Import(in *Import, out *core.Import, s conversion.Scope) error {
	return autoConvert_v1alpha1_Import_To_core_Import(in, out, s)
}

func autoConvert_core_Import_To_v1alpha1_Import(in *core.Import, out *Import, s conversion.Scope) error {
	out.From = in.From
	out.To = in.To
	out.Type = in.Type
	out.Required = in.Required
	if err := Convert_core_Default_To_v1alpha1_Default(&in.Default, &out.Default, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_Import_To_v1alpha1_Import is an autogenerated conversion function.
func Convert_core_Import_To_v1alpha1_Import(in *core.Import, out *Import, s conversion.Scope) error {
	return autoConvert_core_Import_To_v1alpha1_Import(in, out, s)
}

func autoConvert_v1alpha1_LandscapeConfiguration_To_core_LandscapeConfiguration(in *LandscapeConfiguration, out *core.LandscapeConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_LandscapeConfigurationSpec_To_core_LandscapeConfigurationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LandscapeConfiguration_To_core_LandscapeConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_LandscapeConfiguration_To_core_LandscapeConfiguration(in *LandscapeConfiguration, out *core.LandscapeConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_LandscapeConfiguration_To_core_LandscapeConfiguration(in, out, s)
}

func autoConvert_core_LandscapeConfiguration_To_v1alpha1_LandscapeConfiguration(in *core.LandscapeConfiguration, out *LandscapeConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_LandscapeConfigurationSpec_To_v1alpha1_LandscapeConfigurationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_LandscapeConfiguration_To_v1alpha1_LandscapeConfiguration is an autogenerated conversion function.
func Convert_core_LandscapeConfiguration_To_v1alpha1_LandscapeConfiguration(in *core.LandscapeConfiguration, out *LandscapeConfiguration, s conversion.Scope) error {
	return autoConvert_core_LandscapeConfiguration_To_v1alpha1_LandscapeConfiguration(in, out, s)
}

func autoConvert_v1alpha1_LandscapeConfigurationList_To_core_LandscapeConfigurationList(in *LandscapeConfigurationList, out *core.LandscapeConfigurationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.Type)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_LandscapeConfigurationList_To_core_LandscapeConfigurationList is an autogenerated conversion function.
func Convert_v1alpha1_LandscapeConfigurationList_To_core_LandscapeConfigurationList(in *LandscapeConfigurationList, out *core.LandscapeConfigurationList, s conversion.Scope) error {
	return autoConvert_v1alpha1_LandscapeConfigurationList_To_core_LandscapeConfigurationList(in, out, s)
}

func autoConvert_core_LandscapeConfigurationList_To_v1alpha1_LandscapeConfigurationList(in *core.LandscapeConfigurationList, out *LandscapeConfigurationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Type)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_LandscapeConfigurationList_To_v1alpha1_LandscapeConfigurationList is an autogenerated conversion function.
func Convert_core_LandscapeConfigurationList_To_v1alpha1_LandscapeConfigurationList(in *core.LandscapeConfigurationList, out *LandscapeConfigurationList, s conversion.Scope) error {
	return autoConvert_core_LandscapeConfigurationList_To_v1alpha1_LandscapeConfigurationList(in, out, s)
}

func autoConvert_v1alpha1_LandscapeConfigurationSpec_To_core_LandscapeConfigurationSpec(in *LandscapeConfigurationSpec, out *core.LandscapeConfigurationSpec, s conversion.Scope) error {
	out.SecretReferences = *(*[]core.NamespacedName)(unsafe.Pointer(&in.SecretReferences))
	return nil
}

// Convert_v1alpha1_LandscapeConfigurationSpec_To_core_LandscapeConfigurationSpec is an autogenerated conversion function.
func Convert_v1alpha1_LandscapeConfigurationSpec_To_core_LandscapeConfigurationSpec(in *LandscapeConfigurationSpec, out *core.LandscapeConfigurationSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_LandscapeConfigurationSpec_To_core_LandscapeConfigurationSpec(in, out, s)
}

func autoConvert_core_LandscapeConfigurationSpec_To_v1alpha1_LandscapeConfigurationSpec(in *core.LandscapeConfigurationSpec, out *LandscapeConfigurationSpec, s conversion.Scope) error {
	out.SecretReferences = *(*[]NamespacedName)(unsafe.Pointer(&in.SecretReferences))
	return nil
}

// Convert_core_LandscapeConfigurationSpec_To_v1alpha1_LandscapeConfigurationSpec is an autogenerated conversion function.
func Convert_core_LandscapeConfigurationSpec_To_v1alpha1_LandscapeConfigurationSpec(in *core.LandscapeConfigurationSpec, out *LandscapeConfigurationSpec, s conversion.Scope) error {
	return autoConvert_core_LandscapeConfigurationSpec_To_v1alpha1_LandscapeConfigurationSpec(in, out, s)
}

func autoConvert_v1alpha1_NamespacedName_To_core_NamespacedName(in *NamespacedName, out *core.NamespacedName, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha1_NamespacedName_To_core_NamespacedName is an autogenerated conversion function.
func Convert_v1alpha1_NamespacedName_To_core_NamespacedName(in *NamespacedName, out *core.NamespacedName, s conversion.Scope) error {
	return autoConvert_v1alpha1_NamespacedName_To_core_NamespacedName(in, out, s)
}

func autoConvert_core_NamespacedName_To_v1alpha1_NamespacedName(in *core.NamespacedName, out *NamespacedName, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_core_NamespacedName_To_v1alpha1_NamespacedName is an autogenerated conversion function.
func Convert_core_NamespacedName_To_v1alpha1_NamespacedName(in *core.NamespacedName, out *NamespacedName, s conversion.Scope) error {
	return autoConvert_core_NamespacedName_To_v1alpha1_NamespacedName(in, out, s)
}

func autoConvert_v1alpha1_ScriptConfig_To_core_ScriptConfig(in *ScriptConfig, out *core.ScriptConfig, s conversion.Scope) error {
	out.Script = in.Script
	out.Image = in.Image
	return nil
}

// Convert_v1alpha1_ScriptConfig_To_core_ScriptConfig is an autogenerated conversion function.
func Convert_v1alpha1_ScriptConfig_To_core_ScriptConfig(in *ScriptConfig, out *core.ScriptConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ScriptConfig_To_core_ScriptConfig(in, out, s)
}

func autoConvert_core_ScriptConfig_To_v1alpha1_ScriptConfig(in *core.ScriptConfig, out *ScriptConfig, s conversion.Scope) error {
	out.Script = in.Script
	out.Image = in.Image
	return nil
}

// Convert_core_ScriptConfig_To_v1alpha1_ScriptConfig is an autogenerated conversion function.
func Convert_core_ScriptConfig_To_v1alpha1_ScriptConfig(in *core.ScriptConfig, out *ScriptConfig, s conversion.Scope) error {
	return autoConvert_core_ScriptConfig_To_v1alpha1_ScriptConfig(in, out, s)
}

func autoConvert_v1alpha1_TemplateConfig_To_core_TemplateConfig(in *TemplateConfig, out *core.TemplateConfig, s conversion.Scope) error {
	out.Type = in.Type
	out.Config = in.Config
	return nil
}

// Convert_v1alpha1_TemplateConfig_To_core_TemplateConfig is an autogenerated conversion function.
func Convert_v1alpha1_TemplateConfig_To_core_TemplateConfig(in *TemplateConfig, out *core.TemplateConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_TemplateConfig_To_core_TemplateConfig(in, out, s)
}

func autoConvert_core_TemplateConfig_To_v1alpha1_TemplateConfig(in *core.TemplateConfig, out *TemplateConfig, s conversion.Scope) error {
	out.Type = in.Type
	out.Config = in.Config
	return nil
}

// Convert_core_TemplateConfig_To_v1alpha1_TemplateConfig is an autogenerated conversion function.
func Convert_core_TemplateConfig_To_v1alpha1_TemplateConfig(in *core.TemplateConfig, out *TemplateConfig, s conversion.Scope) error {
	return autoConvert_core_TemplateConfig_To_v1alpha1_TemplateConfig(in, out, s)
}

func autoConvert_v1alpha1_Type_To_core_Type(in *Type, out *core.Type, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_TypeSpec_To_core_TypeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_TypeStatus_To_core_TypeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Type_To_core_Type is an autogenerated conversion function.
func Convert_v1alpha1_Type_To_core_Type(in *Type, out *core.Type, s conversion.Scope) error {
	return autoConvert_v1alpha1_Type_To_core_Type(in, out, s)
}

func autoConvert_core_Type_To_v1alpha1_Type(in *core.Type, out *Type, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_TypeSpec_To_v1alpha1_TypeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_core_TypeStatus_To_v1alpha1_TypeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_Type_To_v1alpha1_Type is an autogenerated conversion function.
func Convert_core_Type_To_v1alpha1_Type(in *core.Type, out *Type, s conversion.Scope) error {
	return autoConvert_core_Type_To_v1alpha1_Type(in, out, s)
}

func autoConvert_v1alpha1_TypeCondition_To_core_TypeCondition(in *TypeCondition, out *core.TypeCondition, s conversion.Scope) error {
	out.Type = core.TypeConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_v1alpha1_TypeCondition_To_core_TypeCondition is an autogenerated conversion function.
func Convert_v1alpha1_TypeCondition_To_core_TypeCondition(in *TypeCondition, out *core.TypeCondition, s conversion.Scope) error {
	return autoConvert_v1alpha1_TypeCondition_To_core_TypeCondition(in, out, s)
}

func autoConvert_core_TypeCondition_To_v1alpha1_TypeCondition(in *core.TypeCondition, out *TypeCondition, s conversion.Scope) error {
	out.Type = TypeConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.Reason = in.Reason
	out.Message = in.Message
	return nil
}

// Convert_core_TypeCondition_To_v1alpha1_TypeCondition is an autogenerated conversion function.
func Convert_core_TypeCondition_To_v1alpha1_TypeCondition(in *core.TypeCondition, out *TypeCondition, s conversion.Scope) error {
	return autoConvert_core_TypeCondition_To_v1alpha1_TypeCondition(in, out, s)
}

func autoConvert_v1alpha1_TypeList_To_core_TypeList(in *TypeList, out *core.TypeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.Type)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_TypeList_To_core_TypeList is an autogenerated conversion function.
func Convert_v1alpha1_TypeList_To_core_TypeList(in *TypeList, out *core.TypeList, s conversion.Scope) error {
	return autoConvert_v1alpha1_TypeList_To_core_TypeList(in, out, s)
}

func autoConvert_core_TypeList_To_v1alpha1_TypeList(in *core.TypeList, out *TypeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Type)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_TypeList_To_v1alpha1_TypeList is an autogenerated conversion function.
func Convert_core_TypeList_To_v1alpha1_TypeList(in *core.TypeList, out *TypeList, s conversion.Scope) error {
	return autoConvert_core_TypeList_To_v1alpha1_TypeList(in, out, s)
}

func autoConvert_v1alpha1_TypeSpec_To_core_TypeSpec(in *TypeSpec, out *core.TypeSpec, s conversion.Scope) error {
	out.OpenAPIV3Schema = in.OpenAPIV3Schema
	return nil
}

// Convert_v1alpha1_TypeSpec_To_core_TypeSpec is an autogenerated conversion function.
func Convert_v1alpha1_TypeSpec_To_core_TypeSpec(in *TypeSpec, out *core.TypeSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_TypeSpec_To_core_TypeSpec(in, out, s)
}

func autoConvert_core_TypeSpec_To_v1alpha1_TypeSpec(in *core.TypeSpec, out *TypeSpec, s conversion.Scope) error {
	out.OpenAPIV3Schema = in.OpenAPIV3Schema
	return nil
}

// Convert_core_TypeSpec_To_v1alpha1_TypeSpec is an autogenerated conversion function.
func Convert_core_TypeSpec_To_v1alpha1_TypeSpec(in *core.TypeSpec, out *TypeSpec, s conversion.Scope) error {
	return autoConvert_core_TypeSpec_To_v1alpha1_TypeSpec(in, out, s)
}

func autoConvert_v1alpha1_TypeStatus_To_core_TypeStatus(in *TypeStatus, out *core.TypeStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]core.TypeCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_TypeStatus_To_core_TypeStatus is an autogenerated conversion function.
func Convert_v1alpha1_TypeStatus_To_core_TypeStatus(in *TypeStatus, out *core.TypeStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_TypeStatus_To_core_TypeStatus(in, out, s)
}

func autoConvert_core_TypeStatus_To_v1alpha1_TypeStatus(in *core.TypeStatus, out *TypeStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]TypeCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_core_TypeStatus_To_v1alpha1_TypeStatus is an autogenerated conversion function.
func Convert_core_TypeStatus_To_v1alpha1_TypeStatus(in *core.TypeStatus, out *TypeStatus, s conversion.Scope) error {
	return autoConvert_core_TypeStatus_To_v1alpha1_TypeStatus(in, out, s)
}
