// +build !ignore_autogenerated

/*
Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	json "encoding/json"
	unsafe "unsafe"

	core "github.com/gardener/landscaper/pkg/apis/core"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ComponentDefinition)(nil), (*core.ComponentDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentDefinition_To_core_ComponentDefinition(a.(*ComponentDefinition), b.(*core.ComponentDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ComponentDefinition)(nil), (*ComponentDefinition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ComponentDefinition_To_v1alpha1_ComponentDefinition(a.(*core.ComponentDefinition), b.(*ComponentDefinition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentInstallation)(nil), (*core.ComponentInstallation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentInstallation_To_core_ComponentInstallation(a.(*ComponentInstallation), b.(*core.ComponentInstallation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ComponentInstallation)(nil), (*ComponentInstallation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ComponentInstallation_To_v1alpha1_ComponentInstallation(a.(*core.ComponentInstallation), b.(*ComponentInstallation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentInstallationList)(nil), (*core.ComponentInstallationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentInstallationList_To_core_ComponentInstallationList(a.(*ComponentInstallationList), b.(*core.ComponentInstallationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ComponentInstallationList)(nil), (*ComponentInstallationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ComponentInstallationList_To_v1alpha1_ComponentInstallationList(a.(*core.ComponentInstallationList), b.(*ComponentInstallationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentInstallationSpec)(nil), (*core.ComponentInstallationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentInstallationSpec_To_core_ComponentInstallationSpec(a.(*ComponentInstallationSpec), b.(*core.ComponentInstallationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ComponentInstallationSpec)(nil), (*ComponentInstallationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ComponentInstallationSpec_To_v1alpha1_ComponentInstallationSpec(a.(*core.ComponentInstallationSpec), b.(*ComponentInstallationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ComponentInstallationStatus)(nil), (*core.ComponentInstallationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ComponentInstallationStatus_To_core_ComponentInstallationStatus(a.(*ComponentInstallationStatus), b.(*core.ComponentInstallationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ComponentInstallationStatus)(nil), (*ComponentInstallationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ComponentInstallationStatus_To_v1alpha1_ComponentInstallationStatus(a.(*core.ComponentInstallationStatus), b.(*ComponentInstallationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Condition)(nil), (*core.Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Condition_To_core_Condition(a.(*Condition), b.(*core.Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Condition)(nil), (*Condition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Condition_To_v1alpha1_Condition(a.(*core.Condition), b.(*Condition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CustomType)(nil), (*core.CustomType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CustomType_To_core_CustomType(a.(*CustomType), b.(*core.CustomType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.CustomType)(nil), (*CustomType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_CustomType_To_v1alpha1_CustomType(a.(*core.CustomType), b.(*CustomType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DataType)(nil), (*core.DataType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DataType_To_core_DataType(a.(*DataType), b.(*core.DataType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DataType)(nil), (*DataType)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DataType_To_v1alpha1_DataType(a.(*core.DataType), b.(*DataType), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DataTypeList)(nil), (*core.DataTypeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DataTypeList_To_core_DataTypeList(a.(*DataTypeList), b.(*core.DataTypeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DataTypeList)(nil), (*DataTypeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DataTypeList_To_v1alpha1_DataTypeList(a.(*core.DataTypeList), b.(*DataTypeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DataTypeScheme)(nil), (*core.DataTypeScheme)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DataTypeScheme_To_core_DataTypeScheme(a.(*DataTypeScheme), b.(*core.DataTypeScheme), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DataTypeScheme)(nil), (*DataTypeScheme)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DataTypeScheme_To_v1alpha1_DataTypeScheme(a.(*core.DataTypeScheme), b.(*DataTypeScheme), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Default)(nil), (*core.Default)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Default_To_core_Default(a.(*Default), b.(*core.Default), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Default)(nil), (*Default)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Default_To_v1alpha1_Default(a.(*core.Default), b.(*Default), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DefinitionExport)(nil), (*core.DefinitionExport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DefinitionExport_To_core_DefinitionExport(a.(*DefinitionExport), b.(*core.DefinitionExport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DefinitionExport)(nil), (*DefinitionExport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DefinitionExport_To_v1alpha1_DefinitionExport(a.(*core.DefinitionExport), b.(*DefinitionExport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DefinitionExportMapping)(nil), (*core.DefinitionExportMapping)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DefinitionExportMapping_To_core_DefinitionExportMapping(a.(*DefinitionExportMapping), b.(*core.DefinitionExportMapping), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DefinitionExportMapping)(nil), (*DefinitionExportMapping)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DefinitionExportMapping_To_v1alpha1_DefinitionExportMapping(a.(*core.DefinitionExportMapping), b.(*DefinitionExportMapping), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DefinitionFieldMapping)(nil), (*core.DefinitionFieldMapping)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DefinitionFieldMapping_To_core_DefinitionFieldMapping(a.(*DefinitionFieldMapping), b.(*core.DefinitionFieldMapping), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DefinitionFieldMapping)(nil), (*DefinitionFieldMapping)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DefinitionFieldMapping_To_v1alpha1_DefinitionFieldMapping(a.(*core.DefinitionFieldMapping), b.(*DefinitionFieldMapping), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DefinitionFieldValue)(nil), (*core.DefinitionFieldValue)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DefinitionFieldValue_To_core_DefinitionFieldValue(a.(*DefinitionFieldValue), b.(*core.DefinitionFieldValue), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DefinitionFieldValue)(nil), (*DefinitionFieldValue)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DefinitionFieldValue_To_v1alpha1_DefinitionFieldValue(a.(*core.DefinitionFieldValue), b.(*DefinitionFieldValue), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DefinitionImport)(nil), (*core.DefinitionImport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DefinitionImport_To_core_DefinitionImport(a.(*DefinitionImport), b.(*core.DefinitionImport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DefinitionImport)(nil), (*DefinitionImport)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DefinitionImport_To_v1alpha1_DefinitionImport(a.(*core.DefinitionImport), b.(*DefinitionImport), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DefinitionImportMapping)(nil), (*core.DefinitionImportMapping)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DefinitionImportMapping_To_core_DefinitionImportMapping(a.(*DefinitionImportMapping), b.(*core.DefinitionImportMapping), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DefinitionImportMapping)(nil), (*DefinitionImportMapping)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DefinitionImportMapping_To_v1alpha1_DefinitionImportMapping(a.(*core.DefinitionImportMapping), b.(*DefinitionImportMapping), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DefinitionReference)(nil), (*core.DefinitionReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DefinitionReference_To_core_DefinitionReference(a.(*DefinitionReference), b.(*core.DefinitionReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DefinitionReference)(nil), (*DefinitionReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DefinitionReference_To_v1alpha1_DefinitionReference(a.(*core.DefinitionReference), b.(*DefinitionReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeployItem)(nil), (*core.DeployItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeployItem_To_core_DeployItem(a.(*DeployItem), b.(*core.DeployItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DeployItem)(nil), (*DeployItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DeployItem_To_v1alpha1_DeployItem(a.(*core.DeployItem), b.(*DeployItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeployItemList)(nil), (*core.DeployItemList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeployItemList_To_core_DeployItemList(a.(*DeployItemList), b.(*core.DeployItemList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DeployItemList)(nil), (*DeployItemList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DeployItemList_To_v1alpha1_DeployItemList(a.(*core.DeployItemList), b.(*DeployItemList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeployItemSpec)(nil), (*core.DeployItemSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeployItemSpec_To_core_DeployItemSpec(a.(*DeployItemSpec), b.(*core.DeployItemSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DeployItemSpec)(nil), (*DeployItemSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DeployItemSpec_To_v1alpha1_DeployItemSpec(a.(*core.DeployItemSpec), b.(*DeployItemSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DeployItemStatus)(nil), (*core.DeployItemStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DeployItemStatus_To_core_DeployItemStatus(a.(*DeployItemStatus), b.(*core.DeployItemStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.DeployItemStatus)(nil), (*DeployItemStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_DeployItemStatus_To_v1alpha1_DeployItemStatus(a.(*core.DeployItemStatus), b.(*DeployItemStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Execution)(nil), (*core.Execution)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Execution_To_core_Execution(a.(*Execution), b.(*core.Execution), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.Execution)(nil), (*Execution)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_Execution_To_v1alpha1_Execution(a.(*core.Execution), b.(*Execution), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExecutionItem)(nil), (*core.ExecutionItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExecutionItem_To_core_ExecutionItem(a.(*ExecutionItem), b.(*core.ExecutionItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ExecutionItem)(nil), (*ExecutionItem)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ExecutionItem_To_v1alpha1_ExecutionItem(a.(*core.ExecutionItem), b.(*ExecutionItem), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExecutionList)(nil), (*core.ExecutionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExecutionList_To_core_ExecutionList(a.(*ExecutionList), b.(*core.ExecutionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ExecutionList)(nil), (*ExecutionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ExecutionList_To_v1alpha1_ExecutionList(a.(*core.ExecutionList), b.(*ExecutionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExecutionSpec)(nil), (*core.ExecutionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExecutionSpec_To_core_ExecutionSpec(a.(*ExecutionSpec), b.(*core.ExecutionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ExecutionSpec)(nil), (*ExecutionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ExecutionSpec_To_v1alpha1_ExecutionSpec(a.(*core.ExecutionSpec), b.(*ExecutionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ExecutionStatus)(nil), (*core.ExecutionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ExecutionStatus_To_core_ExecutionStatus(a.(*ExecutionStatus), b.(*core.ExecutionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ExecutionStatus)(nil), (*ExecutionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ExecutionStatus_To_v1alpha1_ExecutionStatus(a.(*core.ExecutionStatus), b.(*ExecutionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ImportState)(nil), (*core.ImportState)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ImportState_To_core_ImportState(a.(*ImportState), b.(*core.ImportState), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ImportState)(nil), (*ImportState)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ImportState_To_v1alpha1_ImportState(a.(*core.ImportState), b.(*ImportState), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LandscapeConfiguration)(nil), (*core.LandscapeConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LandscapeConfiguration_To_core_LandscapeConfiguration(a.(*LandscapeConfiguration), b.(*core.LandscapeConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.LandscapeConfiguration)(nil), (*LandscapeConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_LandscapeConfiguration_To_v1alpha1_LandscapeConfiguration(a.(*core.LandscapeConfiguration), b.(*LandscapeConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LandscapeConfigurationSpec)(nil), (*core.LandscapeConfigurationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LandscapeConfigurationSpec_To_core_LandscapeConfigurationSpec(a.(*LandscapeConfigurationSpec), b.(*core.LandscapeConfigurationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.LandscapeConfigurationSpec)(nil), (*LandscapeConfigurationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_LandscapeConfigurationSpec_To_v1alpha1_LandscapeConfigurationSpec(a.(*core.LandscapeConfigurationSpec), b.(*LandscapeConfigurationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*LandscapeConfigurationStatus)(nil), (*core.LandscapeConfigurationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_LandscapeConfigurationStatus_To_core_LandscapeConfigurationStatus(a.(*LandscapeConfigurationStatus), b.(*core.LandscapeConfigurationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.LandscapeConfigurationStatus)(nil), (*LandscapeConfigurationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_LandscapeConfigurationStatus_To_v1alpha1_LandscapeConfigurationStatus(a.(*core.LandscapeConfigurationStatus), b.(*LandscapeConfigurationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamedObjectReference)(nil), (*core.NamedObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NamedObjectReference_To_core_NamedObjectReference(a.(*NamedObjectReference), b.(*core.NamedObjectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.NamedObjectReference)(nil), (*NamedObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_NamedObjectReference_To_v1alpha1_NamedObjectReference(a.(*core.NamedObjectReference), b.(*NamedObjectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ObjectReference)(nil), (*core.ObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ObjectReference_To_core_ObjectReference(a.(*ObjectReference), b.(*core.ObjectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.ObjectReference)(nil), (*ObjectReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_ObjectReference_To_v1alpha1_ObjectReference(a.(*core.ObjectReference), b.(*ObjectReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OpenAPIV3Schema)(nil), (*core.OpenAPIV3Schema)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OpenAPIV3Schema_To_core_OpenAPIV3Schema(a.(*OpenAPIV3Schema), b.(*core.OpenAPIV3Schema), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.OpenAPIV3Schema)(nil), (*OpenAPIV3Schema)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_OpenAPIV3Schema_To_v1alpha1_OpenAPIV3Schema(a.(*core.OpenAPIV3Schema), b.(*OpenAPIV3Schema), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecretKeySelector)(nil), (*core.SecretKeySelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecretKeySelector_To_core_SecretKeySelector(a.(*SecretKeySelector), b.(*core.SecretKeySelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.SecretKeySelector)(nil), (*SecretKeySelector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_SecretKeySelector_To_v1alpha1_SecretKeySelector(a.(*core.SecretKeySelector), b.(*SecretKeySelector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SecretRef)(nil), (*core.SecretRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SecretRef_To_core_SecretRef(a.(*SecretRef), b.(*core.SecretRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*core.SecretRef)(nil), (*SecretRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_core_SecretRef_To_v1alpha1_SecretRef(a.(*core.SecretRef), b.(*SecretRef), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ComponentDefinition_To_core_ComponentDefinition(in *ComponentDefinition, out *core.ComponentDefinition, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.CustomTypes = *(*[]core.CustomType)(unsafe.Pointer(&in.CustomTypes))
	out.Imports = *(*[]core.DefinitionImport)(unsafe.Pointer(&in.Imports))
	out.Exports = *(*[]core.DefinitionExport)(unsafe.Pointer(&in.Exports))
	out.DefinitionReferences = *(*[]core.DefinitionReference)(unsafe.Pointer(&in.DefinitionReferences))
	out.Executors = in.Executors
	return nil
}

// Convert_v1alpha1_ComponentDefinition_To_core_ComponentDefinition is an autogenerated conversion function.
func Convert_v1alpha1_ComponentDefinition_To_core_ComponentDefinition(in *ComponentDefinition, out *core.ComponentDefinition, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentDefinition_To_core_ComponentDefinition(in, out, s)
}

func autoConvert_core_ComponentDefinition_To_v1alpha1_ComponentDefinition(in *core.ComponentDefinition, out *ComponentDefinition, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.CustomTypes = *(*[]CustomType)(unsafe.Pointer(&in.CustomTypes))
	out.Imports = *(*[]DefinitionImport)(unsafe.Pointer(&in.Imports))
	out.Exports = *(*[]DefinitionExport)(unsafe.Pointer(&in.Exports))
	out.DefinitionReferences = *(*[]DefinitionReference)(unsafe.Pointer(&in.DefinitionReferences))
	out.Executors = in.Executors
	return nil
}

// Convert_core_ComponentDefinition_To_v1alpha1_ComponentDefinition is an autogenerated conversion function.
func Convert_core_ComponentDefinition_To_v1alpha1_ComponentDefinition(in *core.ComponentDefinition, out *ComponentDefinition, s conversion.Scope) error {
	return autoConvert_core_ComponentDefinition_To_v1alpha1_ComponentDefinition(in, out, s)
}

func autoConvert_v1alpha1_ComponentInstallation_To_core_ComponentInstallation(in *ComponentInstallation, out *core.ComponentInstallation, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ComponentInstallationSpec_To_core_ComponentInstallationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ComponentInstallationStatus_To_core_ComponentInstallationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ComponentInstallation_To_core_ComponentInstallation is an autogenerated conversion function.
func Convert_v1alpha1_ComponentInstallation_To_core_ComponentInstallation(in *ComponentInstallation, out *core.ComponentInstallation, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentInstallation_To_core_ComponentInstallation(in, out, s)
}

func autoConvert_core_ComponentInstallation_To_v1alpha1_ComponentInstallation(in *core.ComponentInstallation, out *ComponentInstallation, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_ComponentInstallationSpec_To_v1alpha1_ComponentInstallationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_core_ComponentInstallationStatus_To_v1alpha1_ComponentInstallationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_ComponentInstallation_To_v1alpha1_ComponentInstallation is an autogenerated conversion function.
func Convert_core_ComponentInstallation_To_v1alpha1_ComponentInstallation(in *core.ComponentInstallation, out *ComponentInstallation, s conversion.Scope) error {
	return autoConvert_core_ComponentInstallation_To_v1alpha1_ComponentInstallation(in, out, s)
}

func autoConvert_v1alpha1_ComponentInstallationList_To_core_ComponentInstallationList(in *ComponentInstallationList, out *core.ComponentInstallationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.ComponentInstallation)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ComponentInstallationList_To_core_ComponentInstallationList is an autogenerated conversion function.
func Convert_v1alpha1_ComponentInstallationList_To_core_ComponentInstallationList(in *ComponentInstallationList, out *core.ComponentInstallationList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentInstallationList_To_core_ComponentInstallationList(in, out, s)
}

func autoConvert_core_ComponentInstallationList_To_v1alpha1_ComponentInstallationList(in *core.ComponentInstallationList, out *ComponentInstallationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ComponentInstallation)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_ComponentInstallationList_To_v1alpha1_ComponentInstallationList is an autogenerated conversion function.
func Convert_core_ComponentInstallationList_To_v1alpha1_ComponentInstallationList(in *core.ComponentInstallationList, out *ComponentInstallationList, s conversion.Scope) error {
	return autoConvert_core_ComponentInstallationList_To_v1alpha1_ComponentInstallationList(in, out, s)
}

func autoConvert_v1alpha1_ComponentInstallationSpec_To_core_ComponentInstallationSpec(in *ComponentInstallationSpec, out *core.ComponentInstallationSpec, s conversion.Scope) error {
	out.DefinitionRef = in.DefinitionRef
	out.Imports = *(*[]core.DefinitionImportMapping)(unsafe.Pointer(&in.Imports))
	out.Exports = *(*[]core.DefinitionExportMapping)(unsafe.Pointer(&in.Exports))
	return nil
}

// Convert_v1alpha1_ComponentInstallationSpec_To_core_ComponentInstallationSpec is an autogenerated conversion function.
func Convert_v1alpha1_ComponentInstallationSpec_To_core_ComponentInstallationSpec(in *ComponentInstallationSpec, out *core.ComponentInstallationSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentInstallationSpec_To_core_ComponentInstallationSpec(in, out, s)
}

func autoConvert_core_ComponentInstallationSpec_To_v1alpha1_ComponentInstallationSpec(in *core.ComponentInstallationSpec, out *ComponentInstallationSpec, s conversion.Scope) error {
	out.DefinitionRef = in.DefinitionRef
	out.Imports = *(*[]DefinitionImportMapping)(unsafe.Pointer(&in.Imports))
	out.Exports = *(*[]DefinitionExportMapping)(unsafe.Pointer(&in.Exports))
	return nil
}

// Convert_core_ComponentInstallationSpec_To_v1alpha1_ComponentInstallationSpec is an autogenerated conversion function.
func Convert_core_ComponentInstallationSpec_To_v1alpha1_ComponentInstallationSpec(in *core.ComponentInstallationSpec, out *ComponentInstallationSpec, s conversion.Scope) error {
	return autoConvert_core_ComponentInstallationSpec_To_v1alpha1_ComponentInstallationSpec(in, out, s)
}

func autoConvert_v1alpha1_ComponentInstallationStatus_To_core_ComponentInstallationStatus(in *ComponentInstallationStatus, out *core.ComponentInstallationStatus, s conversion.Scope) error {
	out.Phase = core.ComponentInstallationPhase(in.Phase)
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]core.Condition)(unsafe.Pointer(&in.Conditions))
	out.ConfigGeneration = in.ConfigGeneration
	if err := Convert_v1alpha1_ObjectReference_To_core_ObjectReference(&in.ExportReference, &out.ExportReference, s); err != nil {
		return err
	}
	out.Imports = *(*[]core.ImportState)(unsafe.Pointer(&in.Imports))
	out.InstallationReferences = *(*[]core.NamedObjectReference)(unsafe.Pointer(&in.InstallationReferences))
	if err := Convert_v1alpha1_ObjectReference_To_core_ObjectReference(&in.ExecutionReference, &out.ExecutionReference, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ComponentInstallationStatus_To_core_ComponentInstallationStatus is an autogenerated conversion function.
func Convert_v1alpha1_ComponentInstallationStatus_To_core_ComponentInstallationStatus(in *ComponentInstallationStatus, out *core.ComponentInstallationStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ComponentInstallationStatus_To_core_ComponentInstallationStatus(in, out, s)
}

func autoConvert_core_ComponentInstallationStatus_To_v1alpha1_ComponentInstallationStatus(in *core.ComponentInstallationStatus, out *ComponentInstallationStatus, s conversion.Scope) error {
	out.Phase = ComponentInstallationPhase(in.Phase)
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]Condition)(unsafe.Pointer(&in.Conditions))
	out.ConfigGeneration = in.ConfigGeneration
	if err := Convert_core_ObjectReference_To_v1alpha1_ObjectReference(&in.ExportReference, &out.ExportReference, s); err != nil {
		return err
	}
	out.Imports = *(*[]ImportState)(unsafe.Pointer(&in.Imports))
	out.InstallationReferences = *(*[]NamedObjectReference)(unsafe.Pointer(&in.InstallationReferences))
	if err := Convert_core_ObjectReference_To_v1alpha1_ObjectReference(&in.ExecutionReference, &out.ExecutionReference, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_ComponentInstallationStatus_To_v1alpha1_ComponentInstallationStatus is an autogenerated conversion function.
func Convert_core_ComponentInstallationStatus_To_v1alpha1_ComponentInstallationStatus(in *core.ComponentInstallationStatus, out *ComponentInstallationStatus, s conversion.Scope) error {
	return autoConvert_core_ComponentInstallationStatus_To_v1alpha1_ComponentInstallationStatus(in, out, s)
}

func autoConvert_v1alpha1_Condition_To_core_Condition(in *Condition, out *core.Condition, s conversion.Scope) error {
	out.Type = core.ConditionType(in.Type)
	out.Status = core.ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.LastUpdateTime = in.LastUpdateTime
	out.Reason = in.Reason
	out.Message = in.Message
	out.Codes = *(*[]core.ErrorCode)(unsafe.Pointer(&in.Codes))
	return nil
}

// Convert_v1alpha1_Condition_To_core_Condition is an autogenerated conversion function.
func Convert_v1alpha1_Condition_To_core_Condition(in *Condition, out *core.Condition, s conversion.Scope) error {
	return autoConvert_v1alpha1_Condition_To_core_Condition(in, out, s)
}

func autoConvert_core_Condition_To_v1alpha1_Condition(in *core.Condition, out *Condition, s conversion.Scope) error {
	out.Type = ConditionType(in.Type)
	out.Status = ConditionStatus(in.Status)
	out.LastTransitionTime = in.LastTransitionTime
	out.LastUpdateTime = in.LastUpdateTime
	out.Reason = in.Reason
	out.Message = in.Message
	out.Codes = *(*[]ErrorCode)(unsafe.Pointer(&in.Codes))
	return nil
}

// Convert_core_Condition_To_v1alpha1_Condition is an autogenerated conversion function.
func Convert_core_Condition_To_v1alpha1_Condition(in *core.Condition, out *Condition, s conversion.Scope) error {
	return autoConvert_core_Condition_To_v1alpha1_Condition(in, out, s)
}

func autoConvert_v1alpha1_CustomType_To_core_CustomType(in *CustomType, out *core.CustomType, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1alpha1_OpenAPIV3Schema_To_core_OpenAPIV3Schema(&in.OpenAPIV3Schema, &out.OpenAPIV3Schema, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CustomType_To_core_CustomType is an autogenerated conversion function.
func Convert_v1alpha1_CustomType_To_core_CustomType(in *CustomType, out *core.CustomType, s conversion.Scope) error {
	return autoConvert_v1alpha1_CustomType_To_core_CustomType(in, out, s)
}

func autoConvert_core_CustomType_To_v1alpha1_CustomType(in *core.CustomType, out *CustomType, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_core_OpenAPIV3Schema_To_v1alpha1_OpenAPIV3Schema(&in.OpenAPIV3Schema, &out.OpenAPIV3Schema, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_CustomType_To_v1alpha1_CustomType is an autogenerated conversion function.
func Convert_core_CustomType_To_v1alpha1_CustomType(in *core.CustomType, out *CustomType, s conversion.Scope) error {
	return autoConvert_core_CustomType_To_v1alpha1_CustomType(in, out, s)
}

func autoConvert_v1alpha1_DataType_To_core_DataType(in *DataType, out *core.DataType, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DataTypeScheme_To_core_DataTypeScheme(&in.Scheme, &out.Scheme, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_DataType_To_core_DataType is an autogenerated conversion function.
func Convert_v1alpha1_DataType_To_core_DataType(in *DataType, out *core.DataType, s conversion.Scope) error {
	return autoConvert_v1alpha1_DataType_To_core_DataType(in, out, s)
}

func autoConvert_core_DataType_To_v1alpha1_DataType(in *core.DataType, out *DataType, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_DataTypeScheme_To_v1alpha1_DataTypeScheme(&in.Scheme, &out.Scheme, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_DataType_To_v1alpha1_DataType is an autogenerated conversion function.
func Convert_core_DataType_To_v1alpha1_DataType(in *core.DataType, out *DataType, s conversion.Scope) error {
	return autoConvert_core_DataType_To_v1alpha1_DataType(in, out, s)
}

func autoConvert_v1alpha1_DataTypeList_To_core_DataTypeList(in *DataTypeList, out *core.DataTypeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.DataType)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_DataTypeList_To_core_DataTypeList is an autogenerated conversion function.
func Convert_v1alpha1_DataTypeList_To_core_DataTypeList(in *DataTypeList, out *core.DataTypeList, s conversion.Scope) error {
	return autoConvert_v1alpha1_DataTypeList_To_core_DataTypeList(in, out, s)
}

func autoConvert_core_DataTypeList_To_v1alpha1_DataTypeList(in *core.DataTypeList, out *DataTypeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]DataType)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_DataTypeList_To_v1alpha1_DataTypeList is an autogenerated conversion function.
func Convert_core_DataTypeList_To_v1alpha1_DataTypeList(in *core.DataTypeList, out *DataTypeList, s conversion.Scope) error {
	return autoConvert_core_DataTypeList_To_v1alpha1_DataTypeList(in, out, s)
}

func autoConvert_v1alpha1_DataTypeScheme_To_core_DataTypeScheme(in *DataTypeScheme, out *core.DataTypeScheme, s conversion.Scope) error {
	if err := Convert_v1alpha1_OpenAPIV3Schema_To_core_OpenAPIV3Schema(&in.OpenAPIV3Schema, &out.OpenAPIV3Schema, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_DataTypeScheme_To_core_DataTypeScheme is an autogenerated conversion function.
func Convert_v1alpha1_DataTypeScheme_To_core_DataTypeScheme(in *DataTypeScheme, out *core.DataTypeScheme, s conversion.Scope) error {
	return autoConvert_v1alpha1_DataTypeScheme_To_core_DataTypeScheme(in, out, s)
}

func autoConvert_core_DataTypeScheme_To_v1alpha1_DataTypeScheme(in *core.DataTypeScheme, out *DataTypeScheme, s conversion.Scope) error {
	if err := Convert_core_OpenAPIV3Schema_To_v1alpha1_OpenAPIV3Schema(&in.OpenAPIV3Schema, &out.OpenAPIV3Schema, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_DataTypeScheme_To_v1alpha1_DataTypeScheme is an autogenerated conversion function.
func Convert_core_DataTypeScheme_To_v1alpha1_DataTypeScheme(in *core.DataTypeScheme, out *DataTypeScheme, s conversion.Scope) error {
	return autoConvert_core_DataTypeScheme_To_v1alpha1_DataTypeScheme(in, out, s)
}

func autoConvert_v1alpha1_Default_To_core_Default(in *Default, out *core.Default, s conversion.Scope) error {
	out.Value = *(*json.RawMessage)(unsafe.Pointer(&in.Value))
	return nil
}

// Convert_v1alpha1_Default_To_core_Default is an autogenerated conversion function.
func Convert_v1alpha1_Default_To_core_Default(in *Default, out *core.Default, s conversion.Scope) error {
	return autoConvert_v1alpha1_Default_To_core_Default(in, out, s)
}

func autoConvert_core_Default_To_v1alpha1_Default(in *core.Default, out *Default, s conversion.Scope) error {
	out.Value = *(*json.RawMessage)(unsafe.Pointer(&in.Value))
	return nil
}

// Convert_core_Default_To_v1alpha1_Default is an autogenerated conversion function.
func Convert_core_Default_To_v1alpha1_Default(in *core.Default, out *Default, s conversion.Scope) error {
	return autoConvert_core_Default_To_v1alpha1_Default(in, out, s)
}

func autoConvert_v1alpha1_DefinitionExport_To_core_DefinitionExport(in *DefinitionExport, out *core.DefinitionExport, s conversion.Scope) error {
	if err := Convert_v1alpha1_DefinitionFieldValue_To_core_DefinitionFieldValue(&in.DefinitionFieldValue, &out.DefinitionFieldValue, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_DefinitionExport_To_core_DefinitionExport is an autogenerated conversion function.
func Convert_v1alpha1_DefinitionExport_To_core_DefinitionExport(in *DefinitionExport, out *core.DefinitionExport, s conversion.Scope) error {
	return autoConvert_v1alpha1_DefinitionExport_To_core_DefinitionExport(in, out, s)
}

func autoConvert_core_DefinitionExport_To_v1alpha1_DefinitionExport(in *core.DefinitionExport, out *DefinitionExport, s conversion.Scope) error {
	if err := Convert_core_DefinitionFieldValue_To_v1alpha1_DefinitionFieldValue(&in.DefinitionFieldValue, &out.DefinitionFieldValue, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_DefinitionExport_To_v1alpha1_DefinitionExport is an autogenerated conversion function.
func Convert_core_DefinitionExport_To_v1alpha1_DefinitionExport(in *core.DefinitionExport, out *DefinitionExport, s conversion.Scope) error {
	return autoConvert_core_DefinitionExport_To_v1alpha1_DefinitionExport(in, out, s)
}

func autoConvert_v1alpha1_DefinitionExportMapping_To_core_DefinitionExportMapping(in *DefinitionExportMapping, out *core.DefinitionExportMapping, s conversion.Scope) error {
	if err := Convert_v1alpha1_DefinitionFieldMapping_To_core_DefinitionFieldMapping(&in.DefinitionFieldMapping, &out.DefinitionFieldMapping, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_DefinitionExportMapping_To_core_DefinitionExportMapping is an autogenerated conversion function.
func Convert_v1alpha1_DefinitionExportMapping_To_core_DefinitionExportMapping(in *DefinitionExportMapping, out *core.DefinitionExportMapping, s conversion.Scope) error {
	return autoConvert_v1alpha1_DefinitionExportMapping_To_core_DefinitionExportMapping(in, out, s)
}

func autoConvert_core_DefinitionExportMapping_To_v1alpha1_DefinitionExportMapping(in *core.DefinitionExportMapping, out *DefinitionExportMapping, s conversion.Scope) error {
	if err := Convert_core_DefinitionFieldMapping_To_v1alpha1_DefinitionFieldMapping(&in.DefinitionFieldMapping, &out.DefinitionFieldMapping, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_DefinitionExportMapping_To_v1alpha1_DefinitionExportMapping is an autogenerated conversion function.
func Convert_core_DefinitionExportMapping_To_v1alpha1_DefinitionExportMapping(in *core.DefinitionExportMapping, out *DefinitionExportMapping, s conversion.Scope) error {
	return autoConvert_core_DefinitionExportMapping_To_v1alpha1_DefinitionExportMapping(in, out, s)
}

func autoConvert_v1alpha1_DefinitionFieldMapping_To_core_DefinitionFieldMapping(in *DefinitionFieldMapping, out *core.DefinitionFieldMapping, s conversion.Scope) error {
	out.From = in.From
	out.To = in.To
	return nil
}

// Convert_v1alpha1_DefinitionFieldMapping_To_core_DefinitionFieldMapping is an autogenerated conversion function.
func Convert_v1alpha1_DefinitionFieldMapping_To_core_DefinitionFieldMapping(in *DefinitionFieldMapping, out *core.DefinitionFieldMapping, s conversion.Scope) error {
	return autoConvert_v1alpha1_DefinitionFieldMapping_To_core_DefinitionFieldMapping(in, out, s)
}

func autoConvert_core_DefinitionFieldMapping_To_v1alpha1_DefinitionFieldMapping(in *core.DefinitionFieldMapping, out *DefinitionFieldMapping, s conversion.Scope) error {
	out.From = in.From
	out.To = in.To
	return nil
}

// Convert_core_DefinitionFieldMapping_To_v1alpha1_DefinitionFieldMapping is an autogenerated conversion function.
func Convert_core_DefinitionFieldMapping_To_v1alpha1_DefinitionFieldMapping(in *core.DefinitionFieldMapping, out *DefinitionFieldMapping, s conversion.Scope) error {
	return autoConvert_core_DefinitionFieldMapping_To_v1alpha1_DefinitionFieldMapping(in, out, s)
}

func autoConvert_v1alpha1_DefinitionFieldValue_To_core_DefinitionFieldValue(in *DefinitionFieldValue, out *core.DefinitionFieldValue, s conversion.Scope) error {
	out.Key = in.Key
	out.Type = in.Type
	return nil
}

// Convert_v1alpha1_DefinitionFieldValue_To_core_DefinitionFieldValue is an autogenerated conversion function.
func Convert_v1alpha1_DefinitionFieldValue_To_core_DefinitionFieldValue(in *DefinitionFieldValue, out *core.DefinitionFieldValue, s conversion.Scope) error {
	return autoConvert_v1alpha1_DefinitionFieldValue_To_core_DefinitionFieldValue(in, out, s)
}

func autoConvert_core_DefinitionFieldValue_To_v1alpha1_DefinitionFieldValue(in *core.DefinitionFieldValue, out *DefinitionFieldValue, s conversion.Scope) error {
	out.Key = in.Key
	out.Type = in.Type
	return nil
}

// Convert_core_DefinitionFieldValue_To_v1alpha1_DefinitionFieldValue is an autogenerated conversion function.
func Convert_core_DefinitionFieldValue_To_v1alpha1_DefinitionFieldValue(in *core.DefinitionFieldValue, out *DefinitionFieldValue, s conversion.Scope) error {
	return autoConvert_core_DefinitionFieldValue_To_v1alpha1_DefinitionFieldValue(in, out, s)
}

func autoConvert_v1alpha1_DefinitionImport_To_core_DefinitionImport(in *DefinitionImport, out *core.DefinitionImport, s conversion.Scope) error {
	if err := Convert_v1alpha1_DefinitionFieldValue_To_core_DefinitionFieldValue(&in.DefinitionFieldValue, &out.DefinitionFieldValue, s); err != nil {
		return err
	}
	out.Required = (*bool)(unsafe.Pointer(in.Required))
	if err := Convert_v1alpha1_Default_To_core_Default(&in.Default, &out.Default, s); err != nil {
		return err
	}
	out.ConditionalImports = *(*[]core.DefinitionImport)(unsafe.Pointer(&in.ConditionalImports))
	return nil
}

// Convert_v1alpha1_DefinitionImport_To_core_DefinitionImport is an autogenerated conversion function.
func Convert_v1alpha1_DefinitionImport_To_core_DefinitionImport(in *DefinitionImport, out *core.DefinitionImport, s conversion.Scope) error {
	return autoConvert_v1alpha1_DefinitionImport_To_core_DefinitionImport(in, out, s)
}

func autoConvert_core_DefinitionImport_To_v1alpha1_DefinitionImport(in *core.DefinitionImport, out *DefinitionImport, s conversion.Scope) error {
	if err := Convert_core_DefinitionFieldValue_To_v1alpha1_DefinitionFieldValue(&in.DefinitionFieldValue, &out.DefinitionFieldValue, s); err != nil {
		return err
	}
	out.Required = (*bool)(unsafe.Pointer(in.Required))
	if err := Convert_core_Default_To_v1alpha1_Default(&in.Default, &out.Default, s); err != nil {
		return err
	}
	out.ConditionalImports = *(*[]DefinitionImport)(unsafe.Pointer(&in.ConditionalImports))
	return nil
}

// Convert_core_DefinitionImport_To_v1alpha1_DefinitionImport is an autogenerated conversion function.
func Convert_core_DefinitionImport_To_v1alpha1_DefinitionImport(in *core.DefinitionImport, out *DefinitionImport, s conversion.Scope) error {
	return autoConvert_core_DefinitionImport_To_v1alpha1_DefinitionImport(in, out, s)
}

func autoConvert_v1alpha1_DefinitionImportMapping_To_core_DefinitionImportMapping(in *DefinitionImportMapping, out *core.DefinitionImportMapping, s conversion.Scope) error {
	if err := Convert_v1alpha1_DefinitionFieldMapping_To_core_DefinitionFieldMapping(&in.DefinitionFieldMapping, &out.DefinitionFieldMapping, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_DefinitionImportMapping_To_core_DefinitionImportMapping is an autogenerated conversion function.
func Convert_v1alpha1_DefinitionImportMapping_To_core_DefinitionImportMapping(in *DefinitionImportMapping, out *core.DefinitionImportMapping, s conversion.Scope) error {
	return autoConvert_v1alpha1_DefinitionImportMapping_To_core_DefinitionImportMapping(in, out, s)
}

func autoConvert_core_DefinitionImportMapping_To_v1alpha1_DefinitionImportMapping(in *core.DefinitionImportMapping, out *DefinitionImportMapping, s conversion.Scope) error {
	if err := Convert_core_DefinitionFieldMapping_To_v1alpha1_DefinitionFieldMapping(&in.DefinitionFieldMapping, &out.DefinitionFieldMapping, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_DefinitionImportMapping_To_v1alpha1_DefinitionImportMapping is an autogenerated conversion function.
func Convert_core_DefinitionImportMapping_To_v1alpha1_DefinitionImportMapping(in *core.DefinitionImportMapping, out *DefinitionImportMapping, s conversion.Scope) error {
	return autoConvert_core_DefinitionImportMapping_To_v1alpha1_DefinitionImportMapping(in, out, s)
}

func autoConvert_v1alpha1_DefinitionReference_To_core_DefinitionReference(in *DefinitionReference, out *core.DefinitionReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Reference = in.Reference
	out.Imports = *(*[]core.DefinitionImportMapping)(unsafe.Pointer(&in.Imports))
	out.Exports = *(*[]core.DefinitionExportMapping)(unsafe.Pointer(&in.Exports))
	return nil
}

// Convert_v1alpha1_DefinitionReference_To_core_DefinitionReference is an autogenerated conversion function.
func Convert_v1alpha1_DefinitionReference_To_core_DefinitionReference(in *DefinitionReference, out *core.DefinitionReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_DefinitionReference_To_core_DefinitionReference(in, out, s)
}

func autoConvert_core_DefinitionReference_To_v1alpha1_DefinitionReference(in *core.DefinitionReference, out *DefinitionReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Reference = in.Reference
	out.Imports = *(*[]DefinitionImportMapping)(unsafe.Pointer(&in.Imports))
	out.Exports = *(*[]DefinitionExportMapping)(unsafe.Pointer(&in.Exports))
	return nil
}

// Convert_core_DefinitionReference_To_v1alpha1_DefinitionReference is an autogenerated conversion function.
func Convert_core_DefinitionReference_To_v1alpha1_DefinitionReference(in *core.DefinitionReference, out *DefinitionReference, s conversion.Scope) error {
	return autoConvert_core_DefinitionReference_To_v1alpha1_DefinitionReference(in, out, s)
}

func autoConvert_v1alpha1_DeployItem_To_core_DeployItem(in *DeployItem, out *core.DeployItem, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DeployItemSpec_To_core_DeployItemSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_DeployItemStatus_To_core_DeployItemStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_DeployItem_To_core_DeployItem is an autogenerated conversion function.
func Convert_v1alpha1_DeployItem_To_core_DeployItem(in *DeployItem, out *core.DeployItem, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeployItem_To_core_DeployItem(in, out, s)
}

func autoConvert_core_DeployItem_To_v1alpha1_DeployItem(in *core.DeployItem, out *DeployItem, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_DeployItemSpec_To_v1alpha1_DeployItemSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_core_DeployItemStatus_To_v1alpha1_DeployItemStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_DeployItem_To_v1alpha1_DeployItem is an autogenerated conversion function.
func Convert_core_DeployItem_To_v1alpha1_DeployItem(in *core.DeployItem, out *DeployItem, s conversion.Scope) error {
	return autoConvert_core_DeployItem_To_v1alpha1_DeployItem(in, out, s)
}

func autoConvert_v1alpha1_DeployItemList_To_core_DeployItemList(in *DeployItemList, out *core.DeployItemList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.DeployItem)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_DeployItemList_To_core_DeployItemList is an autogenerated conversion function.
func Convert_v1alpha1_DeployItemList_To_core_DeployItemList(in *DeployItemList, out *core.DeployItemList, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeployItemList_To_core_DeployItemList(in, out, s)
}

func autoConvert_core_DeployItemList_To_v1alpha1_DeployItemList(in *core.DeployItemList, out *DeployItemList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]DeployItem)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_DeployItemList_To_v1alpha1_DeployItemList is an autogenerated conversion function.
func Convert_core_DeployItemList_To_v1alpha1_DeployItemList(in *core.DeployItemList, out *DeployItemList, s conversion.Scope) error {
	return autoConvert_core_DeployItemList_To_v1alpha1_DeployItemList(in, out, s)
}

func autoConvert_v1alpha1_DeployItemSpec_To_core_DeployItemSpec(in *DeployItemSpec, out *core.DeployItemSpec, s conversion.Scope) error {
	out.Type = in.Type
	if err := Convert_v1alpha1_ObjectReference_To_core_ObjectReference(&in.ImportReferences, &out.ImportReferences, s); err != nil {
		return err
	}
	out.Configuration = *(*json.RawMessage)(unsafe.Pointer(&in.Configuration))
	return nil
}

// Convert_v1alpha1_DeployItemSpec_To_core_DeployItemSpec is an autogenerated conversion function.
func Convert_v1alpha1_DeployItemSpec_To_core_DeployItemSpec(in *DeployItemSpec, out *core.DeployItemSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeployItemSpec_To_core_DeployItemSpec(in, out, s)
}

func autoConvert_core_DeployItemSpec_To_v1alpha1_DeployItemSpec(in *core.DeployItemSpec, out *DeployItemSpec, s conversion.Scope) error {
	out.Type = in.Type
	if err := Convert_core_ObjectReference_To_v1alpha1_ObjectReference(&in.ImportReferences, &out.ImportReferences, s); err != nil {
		return err
	}
	out.Configuration = *(*json.RawMessage)(unsafe.Pointer(&in.Configuration))
	return nil
}

// Convert_core_DeployItemSpec_To_v1alpha1_DeployItemSpec is an autogenerated conversion function.
func Convert_core_DeployItemSpec_To_v1alpha1_DeployItemSpec(in *core.DeployItemSpec, out *DeployItemSpec, s conversion.Scope) error {
	return autoConvert_core_DeployItemSpec_To_v1alpha1_DeployItemSpec(in, out, s)
}

func autoConvert_v1alpha1_DeployItemStatus_To_core_DeployItemStatus(in *DeployItemStatus, out *core.DeployItemStatus, s conversion.Scope) error {
	out.Phase = core.ExecutionPhase(in.Phase)
	out.Conditions = *(*[]core.Condition)(unsafe.Pointer(&in.Conditions))
	out.ExportReference = (*core.ObjectReference)(unsafe.Pointer(in.ExportReference))
	return nil
}

// Convert_v1alpha1_DeployItemStatus_To_core_DeployItemStatus is an autogenerated conversion function.
func Convert_v1alpha1_DeployItemStatus_To_core_DeployItemStatus(in *DeployItemStatus, out *core.DeployItemStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_DeployItemStatus_To_core_DeployItemStatus(in, out, s)
}

func autoConvert_core_DeployItemStatus_To_v1alpha1_DeployItemStatus(in *core.DeployItemStatus, out *DeployItemStatus, s conversion.Scope) error {
	out.Phase = ExecutionPhase(in.Phase)
	out.Conditions = *(*[]Condition)(unsafe.Pointer(&in.Conditions))
	out.ExportReference = (*ObjectReference)(unsafe.Pointer(in.ExportReference))
	return nil
}

// Convert_core_DeployItemStatus_To_v1alpha1_DeployItemStatus is an autogenerated conversion function.
func Convert_core_DeployItemStatus_To_v1alpha1_DeployItemStatus(in *core.DeployItemStatus, out *DeployItemStatus, s conversion.Scope) error {
	return autoConvert_core_DeployItemStatus_To_v1alpha1_DeployItemStatus(in, out, s)
}

func autoConvert_v1alpha1_Execution_To_core_Execution(in *Execution, out *core.Execution, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ExecutionSpec_To_core_ExecutionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ExecutionStatus_To_core_ExecutionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Execution_To_core_Execution is an autogenerated conversion function.
func Convert_v1alpha1_Execution_To_core_Execution(in *Execution, out *core.Execution, s conversion.Scope) error {
	return autoConvert_v1alpha1_Execution_To_core_Execution(in, out, s)
}

func autoConvert_core_Execution_To_v1alpha1_Execution(in *core.Execution, out *Execution, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_ExecutionSpec_To_v1alpha1_ExecutionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_core_ExecutionStatus_To_v1alpha1_ExecutionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_Execution_To_v1alpha1_Execution is an autogenerated conversion function.
func Convert_core_Execution_To_v1alpha1_Execution(in *core.Execution, out *Execution, s conversion.Scope) error {
	return autoConvert_core_Execution_To_v1alpha1_Execution(in, out, s)
}

func autoConvert_v1alpha1_ExecutionItem_To_core_ExecutionItem(in *ExecutionItem, out *core.ExecutionItem, s conversion.Scope) error {
	out.Name = in.Name
	out.Type = core.ExecutionType(in.Type)
	out.Configuration = *(*json.RawMessage)(unsafe.Pointer(&in.Configuration))
	return nil
}

// Convert_v1alpha1_ExecutionItem_To_core_ExecutionItem is an autogenerated conversion function.
func Convert_v1alpha1_ExecutionItem_To_core_ExecutionItem(in *ExecutionItem, out *core.ExecutionItem, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExecutionItem_To_core_ExecutionItem(in, out, s)
}

func autoConvert_core_ExecutionItem_To_v1alpha1_ExecutionItem(in *core.ExecutionItem, out *ExecutionItem, s conversion.Scope) error {
	out.Name = in.Name
	out.Type = ExecutionType(in.Type)
	out.Configuration = *(*json.RawMessage)(unsafe.Pointer(&in.Configuration))
	return nil
}

// Convert_core_ExecutionItem_To_v1alpha1_ExecutionItem is an autogenerated conversion function.
func Convert_core_ExecutionItem_To_v1alpha1_ExecutionItem(in *core.ExecutionItem, out *ExecutionItem, s conversion.Scope) error {
	return autoConvert_core_ExecutionItem_To_v1alpha1_ExecutionItem(in, out, s)
}

func autoConvert_v1alpha1_ExecutionList_To_core_ExecutionList(in *ExecutionList, out *core.ExecutionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]core.Execution)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ExecutionList_To_core_ExecutionList is an autogenerated conversion function.
func Convert_v1alpha1_ExecutionList_To_core_ExecutionList(in *ExecutionList, out *core.ExecutionList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExecutionList_To_core_ExecutionList(in, out, s)
}

func autoConvert_core_ExecutionList_To_v1alpha1_ExecutionList(in *core.ExecutionList, out *ExecutionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Execution)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_core_ExecutionList_To_v1alpha1_ExecutionList is an autogenerated conversion function.
func Convert_core_ExecutionList_To_v1alpha1_ExecutionList(in *core.ExecutionList, out *ExecutionList, s conversion.Scope) error {
	return autoConvert_core_ExecutionList_To_v1alpha1_ExecutionList(in, out, s)
}

func autoConvert_v1alpha1_ExecutionSpec_To_core_ExecutionSpec(in *ExecutionSpec, out *core.ExecutionSpec, s conversion.Scope) error {
	out.Executions = *(*[]core.ExecutionItem)(unsafe.Pointer(&in.Executions))
	return nil
}

// Convert_v1alpha1_ExecutionSpec_To_core_ExecutionSpec is an autogenerated conversion function.
func Convert_v1alpha1_ExecutionSpec_To_core_ExecutionSpec(in *ExecutionSpec, out *core.ExecutionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExecutionSpec_To_core_ExecutionSpec(in, out, s)
}

func autoConvert_core_ExecutionSpec_To_v1alpha1_ExecutionSpec(in *core.ExecutionSpec, out *ExecutionSpec, s conversion.Scope) error {
	out.Executions = *(*[]ExecutionItem)(unsafe.Pointer(&in.Executions))
	return nil
}

// Convert_core_ExecutionSpec_To_v1alpha1_ExecutionSpec is an autogenerated conversion function.
func Convert_core_ExecutionSpec_To_v1alpha1_ExecutionSpec(in *core.ExecutionSpec, out *ExecutionSpec, s conversion.Scope) error {
	return autoConvert_core_ExecutionSpec_To_v1alpha1_ExecutionSpec(in, out, s)
}

func autoConvert_v1alpha1_ExecutionStatus_To_core_ExecutionStatus(in *ExecutionStatus, out *core.ExecutionStatus, s conversion.Scope) error {
	out.Phase = core.ExecutionPhase(in.Phase)
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]core.Condition)(unsafe.Pointer(&in.Conditions))
	if err := Convert_v1alpha1_ObjectReference_To_core_ObjectReference(&in.ExportReference, &out.ExportReference, s); err != nil {
		return err
	}
	out.DeployItemReferences = *(*[]core.NamedObjectReference)(unsafe.Pointer(&in.DeployItemReferences))
	return nil
}

// Convert_v1alpha1_ExecutionStatus_To_core_ExecutionStatus is an autogenerated conversion function.
func Convert_v1alpha1_ExecutionStatus_To_core_ExecutionStatus(in *ExecutionStatus, out *core.ExecutionStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ExecutionStatus_To_core_ExecutionStatus(in, out, s)
}

func autoConvert_core_ExecutionStatus_To_v1alpha1_ExecutionStatus(in *core.ExecutionStatus, out *ExecutionStatus, s conversion.Scope) error {
	out.Phase = ExecutionPhase(in.Phase)
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]Condition)(unsafe.Pointer(&in.Conditions))
	if err := Convert_core_ObjectReference_To_v1alpha1_ObjectReference(&in.ExportReference, &out.ExportReference, s); err != nil {
		return err
	}
	out.DeployItemReferences = *(*[]NamedObjectReference)(unsafe.Pointer(&in.DeployItemReferences))
	return nil
}

// Convert_core_ExecutionStatus_To_v1alpha1_ExecutionStatus is an autogenerated conversion function.
func Convert_core_ExecutionStatus_To_v1alpha1_ExecutionStatus(in *core.ExecutionStatus, out *ExecutionStatus, s conversion.Scope) error {
	return autoConvert_core_ExecutionStatus_To_v1alpha1_ExecutionStatus(in, out, s)
}

func autoConvert_v1alpha1_ImportState_To_core_ImportState(in *ImportState, out *core.ImportState, s conversion.Scope) error {
	out.From = in.From
	if err := Convert_v1alpha1_ObjectReference_To_core_ObjectReference(&in.InstallationRef, &out.InstallationRef, s); err != nil {
		return err
	}
	out.ConfigGeneration = in.ConfigGeneration
	return nil
}

// Convert_v1alpha1_ImportState_To_core_ImportState is an autogenerated conversion function.
func Convert_v1alpha1_ImportState_To_core_ImportState(in *ImportState, out *core.ImportState, s conversion.Scope) error {
	return autoConvert_v1alpha1_ImportState_To_core_ImportState(in, out, s)
}

func autoConvert_core_ImportState_To_v1alpha1_ImportState(in *core.ImportState, out *ImportState, s conversion.Scope) error {
	out.From = in.From
	if err := Convert_core_ObjectReference_To_v1alpha1_ObjectReference(&in.InstallationRef, &out.InstallationRef, s); err != nil {
		return err
	}
	out.ConfigGeneration = in.ConfigGeneration
	return nil
}

// Convert_core_ImportState_To_v1alpha1_ImportState is an autogenerated conversion function.
func Convert_core_ImportState_To_v1alpha1_ImportState(in *core.ImportState, out *ImportState, s conversion.Scope) error {
	return autoConvert_core_ImportState_To_v1alpha1_ImportState(in, out, s)
}

func autoConvert_v1alpha1_LandscapeConfiguration_To_core_LandscapeConfiguration(in *LandscapeConfiguration, out *core.LandscapeConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_LandscapeConfigurationSpec_To_core_LandscapeConfigurationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_LandscapeConfigurationStatus_To_core_LandscapeConfigurationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_LandscapeConfiguration_To_core_LandscapeConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_LandscapeConfiguration_To_core_LandscapeConfiguration(in *LandscapeConfiguration, out *core.LandscapeConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_LandscapeConfiguration_To_core_LandscapeConfiguration(in, out, s)
}

func autoConvert_core_LandscapeConfiguration_To_v1alpha1_LandscapeConfiguration(in *core.LandscapeConfiguration, out *LandscapeConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_core_LandscapeConfigurationSpec_To_v1alpha1_LandscapeConfigurationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_core_LandscapeConfigurationStatus_To_v1alpha1_LandscapeConfigurationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_LandscapeConfiguration_To_v1alpha1_LandscapeConfiguration is an autogenerated conversion function.
func Convert_core_LandscapeConfiguration_To_v1alpha1_LandscapeConfiguration(in *core.LandscapeConfiguration, out *LandscapeConfiguration, s conversion.Scope) error {
	return autoConvert_core_LandscapeConfiguration_To_v1alpha1_LandscapeConfiguration(in, out, s)
}

func autoConvert_v1alpha1_LandscapeConfigurationSpec_To_core_LandscapeConfigurationSpec(in *LandscapeConfigurationSpec, out *core.LandscapeConfigurationSpec, s conversion.Scope) error {
	out.SecretReferences = *(*[]core.ObjectReference)(unsafe.Pointer(&in.SecretReferences))
	return nil
}

// Convert_v1alpha1_LandscapeConfigurationSpec_To_core_LandscapeConfigurationSpec is an autogenerated conversion function.
func Convert_v1alpha1_LandscapeConfigurationSpec_To_core_LandscapeConfigurationSpec(in *LandscapeConfigurationSpec, out *core.LandscapeConfigurationSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_LandscapeConfigurationSpec_To_core_LandscapeConfigurationSpec(in, out, s)
}

func autoConvert_core_LandscapeConfigurationSpec_To_v1alpha1_LandscapeConfigurationSpec(in *core.LandscapeConfigurationSpec, out *LandscapeConfigurationSpec, s conversion.Scope) error {
	out.SecretReferences = *(*[]ObjectReference)(unsafe.Pointer(&in.SecretReferences))
	return nil
}

// Convert_core_LandscapeConfigurationSpec_To_v1alpha1_LandscapeConfigurationSpec is an autogenerated conversion function.
func Convert_core_LandscapeConfigurationSpec_To_v1alpha1_LandscapeConfigurationSpec(in *core.LandscapeConfigurationSpec, out *LandscapeConfigurationSpec, s conversion.Scope) error {
	return autoConvert_core_LandscapeConfigurationSpec_To_v1alpha1_LandscapeConfigurationSpec(in, out, s)
}

func autoConvert_v1alpha1_LandscapeConfigurationStatus_To_core_LandscapeConfigurationStatus(in *LandscapeConfigurationStatus, out *core.LandscapeConfigurationStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]core.Condition)(unsafe.Pointer(&in.Conditions))
	out.ConfigGeneration = in.ConfigGeneration
	out.ConfigReference = (*core.ObjectReference)(unsafe.Pointer(in.ConfigReference))
	return nil
}

// Convert_v1alpha1_LandscapeConfigurationStatus_To_core_LandscapeConfigurationStatus is an autogenerated conversion function.
func Convert_v1alpha1_LandscapeConfigurationStatus_To_core_LandscapeConfigurationStatus(in *LandscapeConfigurationStatus, out *core.LandscapeConfigurationStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_LandscapeConfigurationStatus_To_core_LandscapeConfigurationStatus(in, out, s)
}

func autoConvert_core_LandscapeConfigurationStatus_To_v1alpha1_LandscapeConfigurationStatus(in *core.LandscapeConfigurationStatus, out *LandscapeConfigurationStatus, s conversion.Scope) error {
	out.ObservedGeneration = in.ObservedGeneration
	out.Conditions = *(*[]Condition)(unsafe.Pointer(&in.Conditions))
	out.ConfigGeneration = in.ConfigGeneration
	out.ConfigReference = (*ObjectReference)(unsafe.Pointer(in.ConfigReference))
	return nil
}

// Convert_core_LandscapeConfigurationStatus_To_v1alpha1_LandscapeConfigurationStatus is an autogenerated conversion function.
func Convert_core_LandscapeConfigurationStatus_To_v1alpha1_LandscapeConfigurationStatus(in *core.LandscapeConfigurationStatus, out *LandscapeConfigurationStatus, s conversion.Scope) error {
	return autoConvert_core_LandscapeConfigurationStatus_To_v1alpha1_LandscapeConfigurationStatus(in, out, s)
}

func autoConvert_v1alpha1_NamedObjectReference_To_core_NamedObjectReference(in *NamedObjectReference, out *core.NamedObjectReference, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_v1alpha1_ObjectReference_To_core_ObjectReference(&in.Reference, &out.Reference, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_NamedObjectReference_To_core_NamedObjectReference is an autogenerated conversion function.
func Convert_v1alpha1_NamedObjectReference_To_core_NamedObjectReference(in *NamedObjectReference, out *core.NamedObjectReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_NamedObjectReference_To_core_NamedObjectReference(in, out, s)
}

func autoConvert_core_NamedObjectReference_To_v1alpha1_NamedObjectReference(in *core.NamedObjectReference, out *NamedObjectReference, s conversion.Scope) error {
	out.Name = in.Name
	if err := Convert_core_ObjectReference_To_v1alpha1_ObjectReference(&in.Reference, &out.Reference, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_NamedObjectReference_To_v1alpha1_NamedObjectReference is an autogenerated conversion function.
func Convert_core_NamedObjectReference_To_v1alpha1_NamedObjectReference(in *core.NamedObjectReference, out *NamedObjectReference, s conversion.Scope) error {
	return autoConvert_core_NamedObjectReference_To_v1alpha1_NamedObjectReference(in, out, s)
}

func autoConvert_v1alpha1_ObjectReference_To_core_ObjectReference(in *ObjectReference, out *core.ObjectReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha1_ObjectReference_To_core_ObjectReference is an autogenerated conversion function.
func Convert_v1alpha1_ObjectReference_To_core_ObjectReference(in *ObjectReference, out *core.ObjectReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_ObjectReference_To_core_ObjectReference(in, out, s)
}

func autoConvert_core_ObjectReference_To_v1alpha1_ObjectReference(in *core.ObjectReference, out *ObjectReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_core_ObjectReference_To_v1alpha1_ObjectReference is an autogenerated conversion function.
func Convert_core_ObjectReference_To_v1alpha1_ObjectReference(in *core.ObjectReference, out *ObjectReference, s conversion.Scope) error {
	return autoConvert_core_ObjectReference_To_v1alpha1_ObjectReference(in, out, s)
}

func autoConvert_v1alpha1_OpenAPIV3Schema_To_core_OpenAPIV3Schema(in *OpenAPIV3Schema, out *core.OpenAPIV3Schema, s conversion.Scope) error {
	out.JSONSchemaProps = in.JSONSchemaProps
	return nil
}

// Convert_v1alpha1_OpenAPIV3Schema_To_core_OpenAPIV3Schema is an autogenerated conversion function.
func Convert_v1alpha1_OpenAPIV3Schema_To_core_OpenAPIV3Schema(in *OpenAPIV3Schema, out *core.OpenAPIV3Schema, s conversion.Scope) error {
	return autoConvert_v1alpha1_OpenAPIV3Schema_To_core_OpenAPIV3Schema(in, out, s)
}

func autoConvert_core_OpenAPIV3Schema_To_v1alpha1_OpenAPIV3Schema(in *core.OpenAPIV3Schema, out *OpenAPIV3Schema, s conversion.Scope) error {
	out.JSONSchemaProps = in.JSONSchemaProps
	return nil
}

// Convert_core_OpenAPIV3Schema_To_v1alpha1_OpenAPIV3Schema is an autogenerated conversion function.
func Convert_core_OpenAPIV3Schema_To_v1alpha1_OpenAPIV3Schema(in *core.OpenAPIV3Schema, out *OpenAPIV3Schema, s conversion.Scope) error {
	return autoConvert_core_OpenAPIV3Schema_To_v1alpha1_OpenAPIV3Schema(in, out, s)
}

func autoConvert_v1alpha1_SecretKeySelector_To_core_SecretKeySelector(in *SecretKeySelector, out *core.SecretKeySelector, s conversion.Scope) error {
	out.LocalObjectReference = in.LocalObjectReference
	out.Key = in.Key
	return nil
}

// Convert_v1alpha1_SecretKeySelector_To_core_SecretKeySelector is an autogenerated conversion function.
func Convert_v1alpha1_SecretKeySelector_To_core_SecretKeySelector(in *SecretKeySelector, out *core.SecretKeySelector, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecretKeySelector_To_core_SecretKeySelector(in, out, s)
}

func autoConvert_core_SecretKeySelector_To_v1alpha1_SecretKeySelector(in *core.SecretKeySelector, out *SecretKeySelector, s conversion.Scope) error {
	out.LocalObjectReference = in.LocalObjectReference
	out.Key = in.Key
	return nil
}

// Convert_core_SecretKeySelector_To_v1alpha1_SecretKeySelector is an autogenerated conversion function.
func Convert_core_SecretKeySelector_To_v1alpha1_SecretKeySelector(in *core.SecretKeySelector, out *SecretKeySelector, s conversion.Scope) error {
	return autoConvert_core_SecretKeySelector_To_v1alpha1_SecretKeySelector(in, out, s)
}

func autoConvert_v1alpha1_SecretRef_To_core_SecretRef(in *SecretRef, out *core.SecretRef, s conversion.Scope) error {
	if err := Convert_v1alpha1_SecretKeySelector_To_core_SecretKeySelector(&in.SecretRef, &out.SecretRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_SecretRef_To_core_SecretRef is an autogenerated conversion function.
func Convert_v1alpha1_SecretRef_To_core_SecretRef(in *SecretRef, out *core.SecretRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_SecretRef_To_core_SecretRef(in, out, s)
}

func autoConvert_core_SecretRef_To_v1alpha1_SecretRef(in *core.SecretRef, out *SecretRef, s conversion.Scope) error {
	if err := Convert_core_SecretKeySelector_To_v1alpha1_SecretKeySelector(&in.SecretRef, &out.SecretRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_core_SecretRef_To_v1alpha1_SecretRef is an autogenerated conversion function.
func Convert_core_SecretRef_To_v1alpha1_SecretRef(in *core.SecretRef, out *SecretRef, s conversion.Scope) error {
	return autoConvert_core_SecretRef_To_v1alpha1_SecretRef(in, out, s)
}
