#!/bin/bash

# SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

GARDENER_KUBECONFIG_PATH=$1
NAMESPACE=$2
TMP=$3
MAX_NUM_CLUSTERS=$4
NUM_CLUSTERS_START_DELETE_OLDEST=$5
DURATION_FOR_CLUSTER_DELETION=$6
PR_ID=$7

SOURCE_PATH="$(dirname $0)/../.."
cd "${SOURCE_PATH}"
SOURCE_PATH="$(pwd)"

echo "Run create Gardener shoot cluster in ${SOURCE_PATH}"

go run -mod=vendor ./hack/testcluster shootcluster create \
    --kubeconfig=$GARDENER_KUBECONFIG_PATH \
    --namespace=$NAMESPACE \
    --cluster-auth=$TMP \
    --max-num-cluster=$MAX_NUM_CLUSTERS \
    --num-clusters-start-delete-oldest=$NUM_CLUSTERS_START_DELETE_OLDEST \
    --duration-for-cluster-deletion=$DURATION_FOR_CLUSTER_DELETION \
    --pr-id=$PR_ID
