#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

PROJECT_ROOT="$(realpath $(dirname $0)/../..)"

echo "Run install missing software"

# install bash for the get version command
if ! which bash 1>/dev/null; then
  echo "Installing bash... "
  apk add --no-cache --no-progress bash
fi

if ! which openssl 1>/dev/null; then
  echo "Installing openssl... "
  apk add --no-cache --no-progress openssl
fi

if ! which curl 1>/dev/null; then
  echo "Installing curl... "
  apk add --no-cache --no-progress curl
fi

if ! which git 1>/dev/null; then
  echo "Installing git... "
  apk add --no-cache --no-progress git
fi

if ! command -v kubectl &> /dev/null
then
    echo "Kubectl could not be found"
    echo "Try installing it..."
    curl -sSLO https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
fi

if ! command -v helm &> /dev/null
then
    echo "Helm could not be found"
    echo "Try installing it..."
    export DESIRED_VERSION="v3.13.2"
    curl -sS https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
fi

if ! command -v jq &> /dev/null
then
    echo "jq could not be found"
    echo "Try installing it..."
    curl -sSLO https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    install -o root -g root -m 0755 jq-linux64 /usr/local/bin/jq
fi

if ! command -v landscaper-cli &> /dev/null
then
  if [[ $(go env GOOS) == "darwin" ]]; then
    echo "Installing landscaper-cli for darwin"
    curl -sSLO https://github.com/gardener/landscapercli/releases/download/v0.19.0/landscapercli-darwin-amd64.gz
    gunzip landscapercli-darwin-amd64.gz
    chmod 700 landscapercli-darwin-amd64
    mv landscapercli-darwin-amd64 /usr/local/bin/landscaper-cli
  fi

  if [[ $(go env GOOS) == "linux" ]]; then
    echo "Installing landscaper-cli for linux"
    curl -sSLO https://github.com/gardener/landscapercli/releases/download/v0.19.0/landscapercli-linux-amd64.gz
    gunzip landscapercli-linux-amd64.gz
    chmod 700 landscapercli-linux-amd64
    mv landscapercli-linux-amd64 /usr/local/bin/landscaper-cli
  fi
fi

if ! command -v ginkgo &> /dev/null
then
    echo "ginkgo could not be found"
    echo "Try installing it..."
    go install github.com/onsi/ginkgo/v2/ginkgo@v2.2.0
fi

if ! command -v ocm &> /dev/null
then
    echo "ocm could not be found"
    echo "Try installing it..."
    OCM_VERSION=$(NO_PREFIX=true ${PROJECT_ROOT}/hack/extract-module-version.sh github.com/open-component-model/ocm)
    curl -sSfL https://ocm.software/install.sh | OCM_VERSION=${OCM_VERSION} bash
fi
