#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

KUBECONFIG_PATH=$1
REGISTRY_CONFIG=$2
VERSION=$3
SKIP_WAITING_FOR_SYSTEM_COMPONENTS=$4

# to disable set on 1
DISABLE_CLEANUP=0

SOURCE_PATH="$(dirname $0)/../.."
cd "${SOURCE_PATH}"
SOURCE_PATH="$(pwd)"

echo "Run integration tests in source path ${SOURCE_PATH}"

echo "Run integration tests in source path ${SOURCE_PATH}"
ginkgo -timeout=60m -v -progress -no-color -seed=17 -fail-fast ./test/integration  -- \
  --kubeconfig $KUBECONFIG_PATH  \
  ${REGISTRY_CONFIG:+"--registry-config=${REGISTRY_CONFIG}"} \
  ${SKIP_WAITING_FOR_SYSTEM_COMPONENTS:+"--skip-waiting-for-system-components=${SKIP_WAITING_FOR_SYSTEM_COMPONENTS}"} \
  --ls-namespace=ls-system  \
  --ls-version=$VERSION  \
  --ls-run-on-shoot  \
  --disable-cleanup=$DISABLE_CLEANUP


