{{/* SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "landscaper.fullname" . }}-config
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
data:
  config.yaml: {{ include "landscaper-config" . | b64enc }}
