{{/* SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "landscaper.fullname" . }}
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "landscaper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include "landscaper-config" . |  sha256sum }}
        {{- if .Values.agent.registryConfig }}
        checksum/registrysecrets: {{ toJson .Values.agent.registryConfig |  sha256sum }}
        {{- end }}
        {{ range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value}}
        {{- end }}
      labels:
        {{- include "landscaper.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "landscaper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ include "landscaper-agent-image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - "--config=/app/ls/config/config.yaml"
          - "--landscaper-kubeconfig=/app/ls/landscaper-cluster-kubeconfig/kubeconfig"
          - "-v={{ .Values.agent.verbosity }}"
          volumeMounts:
          - name: oci-cache
            mountPath: /app/ls/oci-cache
          - name: config
            mountPath: /app/ls/config
          - name: landscaper-cluster-kubeconfig
            mountPath: /app/ls/landscaper-cluster-kubeconfig
          {{- if .Values.agent.registryConfig.secrets }}
          - name: registrypullsecrets
            mountPath: /app/ls/registry/secrets
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: oci-cache
        emptyDir: {}
      - name: config
        secret:
          secretName: {{ include "landscaper.fullname" . }}-config
      - name: landscaper-cluster-kubeconfig
        secret:
          {{- if .Values.agent.landscaperClusterKubeconfig.kubeconfig }}
          secretName:  {{ include "deployer.fullname" . }}-landscaper-cluster-kubeconfig
          {{- else }}
          secretName:  {{ .Values.agent.landscaperClusterKubeconfig.secretRef.name }}
          {{- end }}
      {{- if .Values.agent.registryConfig.secrets }}
      - name: registrypullsecrets
        secret:
          secretName: {{ include "landscaper.fullname" . }}-registry
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
