apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: contexts.landscaper.gardener.cloud
spec:
  group: landscaper.gardener.cloud
  names:
    kind: Context
    plural: contexts
    shortNames:
    - ctx
    singular: context
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Context is a resource that contains shared information of installations.
          This includes information about the repository context like the context
          itself or secrets to access the oci artifacts. But it can also contain deployer
          specific config.
        properties:
          componentVersionOverwrites:
            description: ComponentVersionOverwritesReference is a reference to a ComponentVersionOverwrites
              object The overwrites object has to be in the same namespace as the
              context. If the string is empty, no overwrites will be used.
            type: string
          configurations:
            additionalProperties:
              description: AnyJSON enhances the json.RawMessages with a dedicated
                openapi definition so that all it is correctly generated
              x-kubernetes-preserve-unknown-fields: true
            description: Configurations contains arbitrary configuration information
              for dedicated purposes given by a string key. The key should use a dns-like
              syntax to express the purpose and avoid conflicts.
            type: object
          registryPullSecrets:
            description: 'RegistryPullSecrets defines a list of registry credentials
              that are used to pull blueprints, component descriptors and jsonschemas
              from the respective registry. For more info see: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
              Note that the type information is used to determine the secret key and
              the type of the secret.'
            items:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                  type: string
              type: object
            type: array
          repositoryContext:
            description: RepositoryContext defines the context of the component repository
              to resolve blueprints.
            type: object
            x-kubernetes-preserve-unknown-fields: true
          useOCM:
            description: UseOCM defines whether OCM is used to process installations
              that reference this context.
            type: boolean
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
