apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: targets.landscaper.gardener.cloud
spec:
  group: landscaper.gardener.cloud
  names:
    kind: Target
    plural: targets
    shortNames:
    - tgt
    - tg
    singular: target
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.type
      name: Type
      type: string
    - jsonPath: .metadata.labels['data\.landscaper\.gardener\.cloud\/context']
      name: Context
      type: string
    - jsonPath: .metadata.labels['data\.landscaper\.gardener\.cloud\/key']
      name: Key
      type: string
    - jsonPath: .metadata.labels['data\.landscaper\.gardener\.cloud\/index']
      name: Idx
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Target defines a specific data object that defines target environment.
          Every deploy item can have a target which is used by the deployer to install
          the specific application.
        properties:
          spec:
            description: TargetSpec contains the definition of a target.
            properties:
              config:
                description: Configuration contains the target type specific configuration.
                  Exactly one of the fields Configuration and SecretRef must be set
                x-kubernetes-preserve-unknown-fields: true
              secretRef:
                description: Reference to a secret containing the target type specific
                  configuration. Exactly one of the fields Configuration and SecretRef
                  must be set
                properties:
                  key:
                    description: Key is the name of the key in the secret that holds
                      the data.
                    type: string
                  name:
                    description: Name is the name of the secret
                    type: string
                required:
                - name
                type: object
              type:
                description: Type is the type of the target that defines its data
                  structure. The actual schema may be defined by a target type crd
                  in the future.
                type: string
            required:
            - type
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
