apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: deployitems.landscaper.gardener.cloud
spec:
  group: landscaper.gardener.cloud
  names:
    kind: DeployItem
    plural: deployitems
    shortNames:
    - di
    singular: deployitem
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.type
      name: Type
      type: string
    - jsonPath: .status.phase
      name: Phase
      type: string
    - jsonPath: .status.exportRef.name
      name: ExportRef
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: DeployItem defines a resource that should be processed by a external
          deployer
        properties:
          spec:
            description: DeployItemSpec contains the definition of a deploy item.
            properties:
              config:
                description: Configuration contains the deployer type specific configuration.
                type: object
                x-kubernetes-embedded-resource: true
                x-kubernetes-preserve-unknown-fields: true
              context:
                description: Context defines the current context of the deployitem.
                type: string
              registryPullSecrets:
                description: 'RegistryPullSecrets defines a list of registry credentials
                  that are used to pull blueprints, component descriptors and jsonschemas
                  from the respective registry. For more info see: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
                  Note that the type information is used to determine the secret key
                  and the type of the secret.'
                items:
                  description: ObjectReference is the reference to a kubernetes object.
                  properties:
                    name:
                      description: Name is the name of the kubernetes object.
                      type: string
                    namespace:
                      description: Namespace is the namespace of kubernetes object.
                      type: string
                  required:
                  - name
                  type: object
                type: array
              target:
                description: Target specifies an optional target of the deploy item.
                  In most cases it contains the secrets to access a evironment. It
                  is also used by the deployers to determine the ownernship.
                properties:
                  name:
                    description: Name is the name of the kubernetes object.
                    type: string
                  namespace:
                    description: Namespace is the namespace of kubernetes object.
                    type: string
                required:
                - name
                type: object
              timeout:
                description: Timeout specifies how long the deployer may take to apply
                  the deploy item. When the time is exceeded, the landscaper will
                  add the abort annotation to the deploy item and later put it in
                  'Failed' if the deployer doesn't handle the abort properly. Value
                  has to be parsable by time.ParseDuration (or 'none' to deactivate
                  the timeout). Defaults to ten minutes if not specified.
                type: string
              type:
                description: Type is the type of the deployer that should handle the
                  item.
                type: string
              updateOnChangeOnly:
                description: UpdateOnChangeOnly specifies if redeployment is executed
                  only if the specification of the deploy item has changed.
                type: boolean
            required:
            - type
            type: object
          status:
            description: 'DeployItemStatus contains the status of a deploy item. todo:
              add operation'
            properties:
              conditions:
                description: Conditions contains the actual condition of a deploy
                  item
                items:
                  description: Condition holds the information about the state of
                    a resource.
                  properties:
                    codes:
                      description: Well-defined error codes in case the condition
                        reports a problem.
                      items:
                        type: string
                      type: array
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    lastUpdateTime:
                      description: Last time the condition was updated.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: DataType of the Shoot condition.
                      type: string
                  required:
                  - type
                  - status
                  - lastTransitionTime
                  - lastUpdateTime
                  - reason
                  - message
                  type: object
                type: array
              deployItemPhase:
                description: DeployerPhase is DEPRECATED and will soon be removed.
                type: string
              deployer:
                description: Deployer describes the deployer that has reconciled the
                  deploy item.
                properties:
                  identity:
                    description: Identity describes the unique identity of the deployer.
                    type: string
                  name:
                    description: Name is the name of the deployer.
                    type: string
                  version:
                    description: Version is the version of the deployer.
                    type: string
                required:
                - identity
                - name
                - version
                type: object
              exportRef:
                description: ExportReference is the reference to the object that contains
                  the exported values.
                properties:
                  name:
                    description: Name is the name of the kubernetes object.
                    type: string
                  namespace:
                    description: Namespace is the namespace of kubernetes object.
                    type: string
                required:
                - name
                type: object
              firstError:
                description: FirstError describes the first error that occurred since
                  JobID was changed the last time.
                properties:
                  codes:
                    description: Well-defined error codes in case the condition reports
                      a problem.
                    items:
                      type: string
                    type: array
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: Last time the condition was updated.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  operation:
                    description: Operation describes the operator where the error
                      occurred.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                required:
                - operation
                - lastTransitionTime
                - lastUpdateTime
                - reason
                - message
                type: object
              jobID:
                description: JobID is the ID of the current working request.
                type: string
              jobIDFinished:
                description: JobIDFinished is the ID of the finished working request.
                type: string
              jobIDGenerationTime:
                description: JobIDGenerationTime is the timestamp when the JobID was
                  set.
                format: date-time
                type: string
              lastError:
                description: LastError describes the last error that occurred.
                properties:
                  codes:
                    description: Well-defined error codes in case the condition reports
                      a problem.
                    items:
                      type: string
                    type: array
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  lastUpdateTime:
                    description: Last time the condition was updated.
                    format: date-time
                    type: string
                  message:
                    description: A human readable message indicating details about
                      the transition.
                    type: string
                  operation:
                    description: Operation describes the operator where the error
                      occurred.
                    type: string
                  reason:
                    description: The reason for the condition's last transition.
                    type: string
                required:
                - operation
                - lastTransitionTime
                - lastUpdateTime
                - reason
                - message
                type: object
              lastErrors:
                description: ErrorHistory describes the last n errors that occurred
                  since JobID was changed the last time.
                items:
                  description: Error holds information about an error that occurred.
                  properties:
                    codes:
                      description: Well-defined error codes in case the condition
                        reports a problem.
                      items:
                        type: string
                      type: array
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another.
                      format: date-time
                      type: string
                    lastUpdateTime:
                      description: Last time the condition was updated.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    operation:
                      description: Operation describes the operator where the error
                        occurred.
                      type: string
                    reason:
                      description: The reason for the condition's last transition.
                      type: string
                  required:
                  - operation
                  - lastTransitionTime
                  - lastUpdateTime
                  - reason
                  - message
                  type: object
                type: array
              lastReconcileTime:
                description: LastReconcileTime indicates when the reconciliation of
                  the last change to the deploy item has started
                format: date-time
                type: string
              observedGeneration:
                description: ObservedGeneration is the most recent generation observed
                  for this DeployItem. It corresponds to the DeployItem generation,
                  which is updated on mutation by the landscaper.
                format: int64
                type: integer
              phase:
                description: Phase is the current phase of the DeployItem
                type: string
              providerStatus:
                description: ProviderStatus contains the provider specific status
                type: object
                x-kubernetes-embedded-resource: true
                x-kubernetes-preserve-unknown-fields: true
            required:
            - observedGeneration
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
