apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: componentversionoverwrites.landscaper.gardener.cloud
spec:
  group: landscaper.gardener.cloud
  names:
    kind: ComponentVersionOverwrites
    plural: componentversionoverwrites
    shortNames:
    - compveroverwrite
    - cvo
    singular: componentversionoverwrite
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ComponentVersionOverwrites are resources that can hold any kind
          json or yaml data.
        properties:
          overwrites:
            description: Overwrites defines a list of component overwrites
            items:
              description: ComponentVersionOverwrite defines an overwrite for a specific
                component and/or version of a component.
              properties:
                component:
                  description: Source defines the component that should be replaced.
                  properties:
                    componentName:
                      description: ComponentName defines the unique of the component
                        containing the resource.
                      type: string
                    repositoryContext:
                      description: RepositoryContext defines the context of the component
                        repository to resolve blueprints.
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    version:
                      description: Version defines the version of the component.
                      type: string
                  type: object
                target:
                  description: Substitution defines the replacement target for the
                    component or version.
                  properties:
                    componentName:
                      description: ComponentName defines the unique of the component
                        containing the resource.
                      type: string
                    repositoryContext:
                      description: RepositoryContext defines the context of the component
                        repository to resolve blueprints.
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    version:
                      description: Version defines the version of the component.
                      type: string
                  type: object
              required:
              - component
              - target
              type: object
            type: array
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
