# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: main
  namespace: default
stringData:
  config: |
    common:
      namespace: default
      baseDomain: demo.landscaper.gcp.dev.k8s.ondemand.com
    extdns:
      dnsClass: host
    creds:
      gcloudDNSSecret: ""
    host:
      kubeconfig: ""
