# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: dns
spec:
  blueprintRef: external-dns-management:0.7.11

  imports:
  - from: common.namespace
    to: namespace

  - from: host.kubeconfig
    to: kubeconfig

  - from: extdns.dnsClass
    to: extdns.dnsClass

  - from: creds.gcloudDNSSecret
    to: gcloudDNSSecret

  - from: common.baseDomain
    to: baseDomain

  exports:
  - from: dnsClass
    to: dnsClass

  staticData:
  - valueFrom:
      secretKeyRef:
        name: main-secrets
        key: config
  - value:
      common:
        namespace: default
        baseDomain: demo.landscaper.gcp.dev.k8s.ondemand.com
      extdns:
        dnsClass: host
