# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: nginx
spec:
  blueprintRef: nginx-ingress-controller:0.5.2

  imports:
  - from: common.namespace
    to: namespace
  - from: host.kubeconfig
    to: kubeconfig
  - from: dnsClass
    to: dnsClass
  - from: common.baseDomain
    to: baseDomain

  exports:
  - from: ingressClass
    to: ingressClass

  staticData:
  - valueFrom:
      secretKeyRef:
        name: main-secrets
        key: config
  - value:
      common:
        namespace: default
        baseDomain: demo.landscaper.gcp.dev.k8s.ondemand.com
      nginx:
        ingressClass: "nginx"