apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
   # The "hostingCluster" specifies the target Kubernetes cluster into which the landscaper service will be installed.
  - name: hostingCluster
    required: true
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  # The "hostingClusterNamespace" is the namespace in the hosting cluster into which the landscaper service is getting installed.
  # Only one landscaper server per namespace can be installed.
  - name: hostingClusterNamespace
    required: true
    type: data
    schema:
      type: string

  # Specifies whether the "hostingClusterNamespace" is getting deleted before the installation.
  - name: deleteHostingClusterNamespace
    type: data
    schema:
      type: boolean

  # The "virtualClusterNamespace" is the namespace in the virtual cluster into which the landscaper resources are getting installed.
  - name: virtualClusterNamespace
    required: true
    type: data
    schema:
      type: string

  # The underlying infrastructure provider of the "hostingCluster" Kubernetes cluster.
  # Currently, supported values: "gcp", "aws", "alicloud"
  - name: providerType
    type: data
    required: true
    schema:
      type: string

  # The DNS domain at which the landscaper service should be accessible.
  # Used for certificate generation.
  - name: dnsAccessDomain
    type: data
    required: true
    schema:
      type: string

  # The landscaper registry configuration.
  - name: registryConfig
    type: data
    schema:
      $ref: "cd://resources/registry-config-definition"

  # The landscaper deployment configuration.
  - name: landscaperConfig
    type: data
    schema:
      $ref: "cd://resources/landscaper-config-definition"

exports:
  # "landscaperClusterEndpoint" is the API server endpoint at which the landscaper is available.
  - name: landscaperClusterEndpoint
    type: data
    schema:
      type: string

  # "landscaperClusterKubeconfig" is the Kubernetes kubeconfig which can be used to connect to the API server (Base64 encoded).
  - name: landscaperClusterKubeconfig
    type: data
    schema:
      type: string

exportExecutions:
  - name: export
    type: GoTemplate
    template: |
      exports:
        landscaperClusterEndpoint: {{ .values.dataobjects.virtualGardenEndpoint }}
        landscaperClusterKubeconfig: {{ .values.dataobjects.landscaperUserKubeconfigYaml | b64enc }}

subinstallations:
  - file: /virtual-garden-subinst.yaml
  - file: /landscaper-rbac-subinst.yaml
  - file: /landscaper-deployment-subinst.yaml
