apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
   # The "hostingCluster" specifies the target Kubernetes cluster into which the landscaper service will be installed.
  - name: hostingCluster
    required: true
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: gardenerServiceAccount
    required: true
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: hostingClusterNamespace
    required: true
    type: data
    schema:
      description: |
        The "hostingClusterNamespace" is the namespace in the hosting cluster into which the landscaper service is getting installed.
        Only one landscaper server per namespace can be installed.
      type: string

  - name: targetClusterNamespace
    required: true
    type: data
    schema:
      description: |
        The "targetClusterNamespace" is the namespace in the target shoot cluster into which the landscaper resources are getting installed.
      type: string

  - name: shootName
    required: true
    type: data
    schema:
      type: string

  - name: shootNamespace
    required: true
    type: data
    schema:
      type: string

  - name: shootLabels
    required: false
    type: data
    schema:
      type: object

  - name: shootConfig
    type: data
    schema:
      description: |
        The "shootConfig" Specifies the gardener shoot configuration.
      $ref: "cd://resources/shoot-config-definition"

  - name: registryConfig
    type: data
    schema:
      description: |
        The landscaper registry configuration.
      $ref: "cd://resources/registry-config-definition"

  - name: landscaperConfig
    type: data
    schema:
      description: |
        The landscaper deployment configuration.
      $ref: "cd://resources/landscaper-config-definition"

exports:
  - name: landscaperClusterEndpoint
    type: data
    schema:
      description: |
        The API server endpoint at which the landscaper is available.
      type: string

  - name: landscaperClusterKubeconfig
    type: data
    schema:
      description: |
        The Kubernetes kubeconfig which can be used to connect to the API server (Base64 encoded).
      type: string

exportExecutions:
  - name: export
    type: GoTemplate
    template: |
      exports:
        landscaperClusterEndpoint: {{ .values.dataobjects.shootClusterEndpoint }}
        landscaperClusterKubeconfig: {{ .values.dataobjects.landscaperUserKubeconfigYaml | b64enc }}

subinstallations:
  - file: /shoot-cluster-subinst.yaml
  - file: /landscaper-rbac-subinst.yaml
  - file: /landscaper-deployment-subinst.yaml
