apiVersion: landscaper.gardener.cloud/v1alpha1
kind: InstallationTemplate

name: landscaper-deployment

blueprint:
  ref: cd://resources/landscaper-blueprint

imports:
  targets:
    - name: hostingCluster
      target: hostingCluster
  data:
    - name: hostingClusterNamespace
      dataRef: hostingClusterNamespace
    - name: virtualClusterNamespace
      dataRef: virtualClusterNamespace
    - name: landscaperControllerKubeconfigYaml
      dataRef: landscaperControllerKubeconfigYaml
    - name: landscaperWebhooksKubeconfigYaml
      dataRef: landscaperWebhooksKubeconfigYaml
    - name: registryConfig
      dataRef: registryConfig
    - name: landscaperConfig
      dataRef: landscaperConfig
