apiVersion: landscaper.gardener.cloud/v1alpha1
kind: InstallationTemplate

name: landscaper-rbac

blueprint:
  ref: cd://resources/rbac-blueprint

imports:
  targets:
    - name: shootCluster
      target: shootCluster
  data:
    - name: targetClusterNamespace
      dataRef: targetClusterNamespace
    - name: shootClusterEndpoint
      dataRef: shootClusterEndpoint

exports:
  data:
    - name: landscaperControllerKubeconfigYaml
      dataRef: landscaperControllerKubeconfigYaml
    - name: landscaperWebhooksKubeconfigYaml
      dataRef: landscaperWebhooksKubeconfigYaml
    - name: landscaperUserKubeconfigYaml
      dataRef: landscaperUserKubeconfigYaml
