apiVersion: landscaper.gardener.cloud/v1alpha1
kind: InstallationTemplate

name: virtual-garden

blueprint:
  ref: cd://componentReferences/virtual-garden/resources/blueprint

imports:
  targets:
    - name: cluster
      target: hostingCluster
  data:
    - name: importHostingClusterNamespace
      dataRef: hostingClusterNamespace
    - name: importProviderType
      dataRef: providerType
    - name: importDeleteNamespace
      dataRef: deleteHostingClusterNamespace
    - name: importDnsAccessDomain
      dataRef: dnsAccessDomain

importDataMappings:
  hostingCluster:
    namespace: (( importHostingClusterNamespace ))
    infrastructureProvider: (( importProviderType ))

  virtualGarden:
    deleteNamespace: (( importDeleteNamespace ))
    etcd:
      storageClassName: (( "landscaper-" importHostingClusterNamespace))
      handleETCDPersistentVolumes: true
    kubeAPIServer:
      replicas: 1
      dnsAccessDomain: (( importDnsAccessDomain ))
      gardenerControlplane:
        validatingWebhookEnabled: true
        mutatingWebhookEnabled: true

exports:
  data:
    - name: virtualGardenEndpoint
      dataRef: virtualGardenEndpoint
  targets:
    - name: virtualGardenKubeconfig
      target: virtualGardenKubeconfig
