{{/* SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.serviceAccount.create -}}
{{- if not (has "all" .Values.disableWebhooks) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "landscaper.webhooks.fullname" . }}
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
  - "validatingwebhookconfigurations"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "*"
{{- end -}}
{{- end -}}