{{/* SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors

 SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "landscaper.fullname" . }}
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
rules:
- apiGroups:
  - landscaper.gardener.cloud
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - "secrets"
  - "configmaps"
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - ""
  resources:
  - "serviceaccounts"
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - "secrets"
  verbs:
  - "*"
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - "clusterroles"
  - "clusterrolebindings"
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
# The agent contains a helm deployer to deploy other deployers.
# Its unknown what deployers might need we have to give the agent all possible permissions for resources.
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
{{-  end -}}