# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "landscaper.serviceAccountName" . }}
  labels:
    {{- include "landscaper.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "landscaper.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "landscaper.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
