apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: hello-world
  namespace: example
  annotations:
    landscaper.gardener.cloud/operation: reconcile

spec:

  componentDescriptor:
    ref:
      componentName: github.com/gardener/landscaper-examples/guided-tour/external-blueprint
      version: 1.0.0
      repositoryContext:
        baseUrl: eu.gcr.io/gardener-project/landscaper/examples
        type: ociRegistry

  blueprint:
    ref:
      resourceName: blueprint

  # Set values for the import parameters of the blueprint
  imports:
    targets:
      - name: cluster        # name of an import parameter of the blueprint
        target: my-cluster   # name of the Target custom resource containing the kubeconfig of the target cluster
