apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint
jsonSchema: "https://json-schema.org/draft/2019-09/schema"

imports:
  - name: redRootCluster
    type: target
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: blueRootCluster
    type: target
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: greenRootCluster
    type: target
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: namespace
    type: data
    schema:
      type: string

subinstallations:
  - file: /subinst.yaml
