charts:
  echo-server-extended:
    installation-name: automation-simple-helm
    installation-namespace: cu-example

    release-name: automation-simple
    release-namespace: example

    # This target need not necessarily occur in the targets section,
    target: my-cluster

    # optional
    values:
      text: first example

  next-chart:
    ...

targets:
  - name: my-cluster
    kubeconfig-path: ...
  ...

credentials:
  # credentials to read resources (helm chart, component version, ...)
