kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  namespace: {{ .namespace }}
  name: {{ .name }}
  annotations:
    shoot.gardener.cloud/cleanup-extended-apis-finalize-grace-period-seconds: '180'
spec:
  provider:
    type: gcp
    infrastructureConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        workers: 10.180.0.0/16
    controlPlaneConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      zone: europe-west1-b
    workers:
      - name: worker-r27th
        minimum: 1
        maximum: 1
        maxSurge: 1
        machine:
          type: n1-standard-4
          image:
            name: gardenlinux
            version: 1312.3.0
          architecture: amd64
        zones:
          - europe-west1-b
        cri:
          name: containerd
        volume:
          type: pd-balanced
          size: 50Gi
  networking:
    nodes: 10.180.0.0/16
    type: calico
  cloudProfileName: gcp
  region: europe-west1
  secretBindingName: laas-canary
  kubernetes:
    version: "1.27"
  purpose: evaluation
  addons:
    kubernetesDashboard:
      enabled: false
    nginxIngress:
      enabled: {{ .nginxIngressEnabled }}
  maintenance:
    timeWindow:
      begin: 010000+0200
      end: 020000+0200
    autoUpdate:
      kubernetesVersion: true
      machineImageVersion: true
  hibernation:
    schedules:
      - start: 00 {{ .hour }} * * 1,2,3,4,5,6,0
        location: Europe/Berlin
